import type { Station, ScheduleEntry, FareTier } from "./blue-line";

export const redLineData = {
  name: "Red Line",
  fullName: "Lagos Red Line Rail",
  color: "#CC1F1F",
  status: "Under Construction" as const,
  operator: "Lagos Metropolitan Area Transport Authority (LAMATA)",
  expectedOpening: "2025–2026",
  length: "37 km",
  totalStations: 11,
  type: "Commuter Rail",
  description:
    "The Lagos Red Line is a commuter rail system running from Agbado in the northwest to Marina on Lagos Island. It follows the existing Nigerian Railway Corporation (NRC) track corridor and will serve some of the most densely populated communities in Lagos, including Agege, Mushin, Yaba and Lagos Island.",
  overview: [
    { label: "Line Length",       value: "37 km" },
    { label: "Stations",          value: "11" },
    { label: "Journey Time",      value: "~50 minutes end to end" },
    { label: "Type",              value: "Commuter Rail" },
    { label: "Expected Opening",  value: "2025–2026" },
    { label: "Status",            value: "Under Construction" },
  ],
  stations: [
    {
      id: "agbado",
      name: "Agbado",
      zone: 1,
      interchange: ["Bus Connections"],
      facilities: ["Ticket Office", "Waiting Lounge", "Parking"],
      coordinates: { lat: 6.6600, lng: 3.2900 },
      isTerminal: true,
    },
    {
      id: "iju",
      name: "Iju",
      zone: 1,
      facilities: ["Ticket Office", "Waiting Lounge"],
      coordinates: { lat: 6.6400, lng: 3.3100 },
    },
    {
      id: "agege-red",
      name: "Agege",
      zone: 2,
      interchange: ["Blue Line Interchange (future)"],
      facilities: ["Ticket Office", "Waiting Lounge", "CCTV"],
      coordinates: { lat: 6.6193, lng: 3.3192 },
    },
    {
      id: "mushin",
      name: "Mushin",
      zone: 2,
      facilities: ["Ticket Office", "Waiting Lounge", "Security"],
      coordinates: { lat: 6.5277, lng: 3.3561 },
    },
    {
      id: "oshodi-red",
      name: "Oshodi",
      zone: 2,
      interchange: ["Blue Line Interchange", "BRT Hub"],
      facilities: ["Ticket Office", "Waiting Lounge", "Security", "CCTV", "Disability Access"],
      coordinates: { lat: 6.5570, lng: 3.3480 },
    },
    {
      id: "yaba",
      name: "Yaba",
      zone: 3,
      interchange: ["Bus Connections"],
      facilities: ["Ticket Office", "Waiting Lounge", "Security", "CCTV"],
      coordinates: { lat: 6.5095, lng: 3.3711 },
    },
    {
      id: "ebute-metta-red",
      name: "Ebute Metta",
      zone: 3,
      interchange: ["Blue Line Interchange"],
      facilities: ["Ticket Office", "Waiting Lounge", "Security", "CCTV"],
      coordinates: { lat: 6.4784, lng: 3.3700 },
    },
    {
      id: "oyingbo-red",
      name: "Oyingbo",
      zone: 3,
      facilities: ["Ticket Office", "Waiting Lounge"],
      coordinates: { lat: 6.4900, lng: 3.3750 },
    },
    {
      id: "iddo-red",
      name: "Iddo",
      zone: 3,
      interchange: ["NRC Terminus", "Blue Line"],
      facilities: ["Ticket Office", "Waiting Lounge", "Security", "CCTV", "Parking"],
      coordinates: { lat: 6.4744, lng: 3.3828 },
    },
    {
      id: "lagos-island-red",
      name: "Lagos Island",
      zone: 4,
      facilities: ["Ticket Office", "Waiting Lounge", "Security"],
      coordinates: { lat: 6.4531, lng: 3.3958 },
    },
    {
      id: "marina-red",
      name: "Marina",
      zone: 4,
      interchange: ["Blue Line Terminal", "Ferry Terminal"],
      facilities: ["Ticket Office", "Waiting Lounge", "Security", "CCTV", "Disability Access"],
      coordinates: { lat: 6.4509, lng: 3.3960 },
      isTerminal: true,
    },
  ] as Station[],

  schedule: [
    { day: "Weekday",  firstTrain: "05:00",  lastTrain: "23:00",  frequency: "Every 15–20 minutes (projected)" },
    { day: "Saturday", firstTrain: "06:00",  lastTrain: "22:00",  frequency: "Every 20–30 minutes (projected)" },
    { day: "Sunday",   firstTrain: "07:00",  lastTrain: "21:00",  frequency: "Every 30 minutes (projected)" },
  ] as ScheduleEntry[],

  fares: [
    { zones: "Zone 1–2 (1–3 stops)",  fare: 150 },
    { zones: "Zone 1–3 (4–7 stops)",  fare: 300 },
    { zones: "Zone 1–4 (8–11 stops)", fare: 400 },
    { zones: "Monthly Pass",           fare: 8000 },
    { zones: "Student Monthly",        fare: 5000 },
  ] as FareTier[],

  rules: [
    "No food or drinks on trains",
    "No smoking in stations or on trains",
    "Priority seating for elderly, pregnant and disabled passengers",
    "Children under 5 travel free with a paying adult",
    "Valid token or card required before boarding",
    "Platform doors must be clear before train departure",
  ],
};
