export type Officer = {
  name: string;
  title: string;
  phone?: string;
  email?: string;
  verified?: boolean;
};

export type Entity = {
  id: string;
  name: string;
  category: "ministry" | "agency" | "parastatal";
  description: string;
  location: string;
  address: string;
  phone: string;
  email: string;
  website?: string;
  officers: Officer[];
  block?: string;
  verified: boolean;
  needsVerification: boolean;
  lastUpdated: string;
};

export const entities: Entity[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // MINISTRIES (23 total — verified against 2026 Lagos State Budget & Wikipedia)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "min-finance",
    name: "Ministry of Finance",
    category: "ministry",
    description: "Responsible for formulating and executing financial policies, managing the state's revenue and expenditure.",
    location: "Alausa, Ikeja",
    address: "Block 18, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://finance.lagosstate.gov.ng",
    officers: [
      { name: "Abayomi Oluyomi", title: "Commissioner for Finance", verified: true },
      { name: "Mrs. Abosede Adeleke", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 18",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-economic-planning",
    name: "Ministry of Economic Planning and Budget",
    category: "ministry",
    description: "Coordinates economic planning, budget preparation and implementation for sustainable growth in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 19, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "01-4963429",
    email: "info@lagosstate.gov.ng",
    website: "https://mepb.lagosstate.gov.ng",
    officers: [
      { name: "Mosopefolu George", title: "Commissioner for Economic Planning & Budget", verified: true },
    ],
    block: "Block 19",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-health",
    name: "Ministry of Health",
    category: "ministry",
    description: "Oversees health policy, hospital administration, and public health services across Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 4, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://health.lagosstate.gov.ng",
    officers: [
      { name: "Prof. Akin Abayomi", title: "Commissioner for Health", verified: true },
      { name: "Dr. Olusegun Ogboye", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 4",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-basic-education",
    name: "Ministry of Basic and Secondary Education",
    category: "ministry",
    description: "Oversees primary and secondary education, curriculum development, and teacher training in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 5, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "Jamiu Alli-Balogun", title: "Commissioner for Basic and Secondary Education", verified: true },
    ],
    block: "Block 5",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-education",
    name: "Ministry of Education",
    category: "ministry",
    description: "Oversees tertiary education, technical education, and educational policy in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 5, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://education.lagosstate.gov.ng",
    officers: [
      { name: "Folashade Adefisayo", title: "Commissioner for Education", verified: true },
      { name: "Mr. Adesola Olusanya", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 5",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-works",
    name: "Ministry of Works and Infrastructure",
    category: "ministry",
    description: "Plans, constructs, and maintains roads, bridges, drains and public infrastructure.",
    location: "Alausa, Ikeja",
    address: "Block 16, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://works.lagosstate.gov.ng",
    officers: [
      { name: "Ope George", title: "Commissioner for Works & Infrastructure", verified: true },
      { name: "Mr. Biodun Junaid", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 16",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-agric",
    name: "Ministry of Agriculture and Food Systems",
    category: "ministry",
    description: "Responsible for agricultural development, food security, and rural development policies in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 8, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "+234 802 481 7093",
    email: "agric@lagosstate.gov.ng",
    website: "https://agriculture.lagosstate.gov.ng",
    officers: [
      { name: "Abisola Olusanya", title: "Commissioner for Agriculture and Food Systems", verified: true },
      { name: "Mr. Hakeem Adeniran", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 8",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-justice",
    name: "Ministry of Justice",
    category: "ministry",
    description: "Provides legal advice to the government, prosecutes criminal cases, and oversees the judicial system.",
    location: "Alausa, Ikeja",
    address: "Block 2, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "Lawal Pedro (SAN)", title: "Attorney General & Commissioner for Justice", verified: true },
    ],
    block: "Block 2",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-housing",
    name: "Ministry of Housing",
    category: "ministry",
    description: "Develops housing policies, manages state housing estates, and regulates real estate development.",
    location: "Alausa, Ikeja",
    address: "Block 13, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://housing.lagosstate.gov.ng",
    officers: [
      { name: "Moruf Akinderu-Fatai", title: "Commissioner for Housing", verified: true },
      { name: "Mrs. Seun Osibona", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 13",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-transport",
    name: "Ministry of Transportation",
    category: "ministry",
    description: "Manages transportation infrastructure, traffic management, and public transport systems.",
    location: "Alausa, Ikeja",
    address: "Block 6, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://transportation.lagosstate.gov.ng",
    officers: [
      { name: "Oluwaseun Osiyemi", title: "Commissioner for Transportation", verified: true },
      { name: "Mr. Olawale Musa", title: "Permanent Secretary", verified: false },
    ],
    block: "Block 6",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-environment",
    name: "Ministry of Environment and Water Resources",
    category: "ministry",
    description: "Oversees environmental protection, pollution control, water resources management, and sanitation.",
    location: "Alausa, Ikeja",
    address: "Block 16, The Secretariat Annex, Alausa, Ikeja, Lagos",
    phone: "+234 810 255 3775",
    email: "lagosstateministryoftheenviron@gmail.com",
    officers: [
      { name: "Tokunbo Wahab", title: "Commissioner for Environment & Water Resources", verified: true },
    ],
    block: "Block 16",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-commerce",
    name: "Ministry of Commerce, Industry and Cooperatives",
    category: "ministry",
    description: "Promotes trade, industrial development, and cooperative societies in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 14, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://mcic.lagosstate.gov.ng",
    officers: [
      { name: "Folashade Ambrose-Medebem", title: "Commissioner for Commerce, Industry & Cooperatives", verified: true },
    ],
    block: "Block 14",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-energy",
    name: "Ministry of Energy and Mineral Resources",
    category: "ministry",
    description: "Formulates policies on energy generation, distribution, and mineral resource management.",
    location: "Alausa, Ikeja",
    address: "Block 15, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://memr.lagosstate.gov.ng",
    officers: [
      { name: "Biodun Ogunleye", title: "Commissioner for Energy & Mineral Resources", verified: true },
    ],
    block: "Block 15",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-science",
    name: "Ministry of Science and Technology",
    category: "ministry",
    description: "Promotes scientific research, technological innovation, and ICT development in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 15, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://most.lagosstate.gov.ng",
    officers: [
      { name: "Tunbosun Alake", title: "Commissioner for Science & Technology", verified: true },
    ],
    block: "Block 15",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-information",
    name: "Ministry of Information and Strategy",
    category: "ministry",
    description: "Manages government communications, media relations, and public information dissemination.",
    location: "Alausa, Ikeja",
    address: "Block 3, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "Gbenga Omotoso", title: "Commissioner for Information & Strategy", verified: true },
    ],
    block: "Block 3",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-physical-planning",
    name: "Ministry of Physical Planning and Urban Development",
    category: "ministry",
    description: "Regulates physical development, urban planning, and building control in Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 17, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://mppud.lagosstate.gov.ng",
    officers: [
      { name: "Oluyinka Abiodun Olumide", title: "Commissioner for Physical Planning & Urban Development", verified: true },
    ],
    block: "Block 17",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-local-govt",
    name: "Ministry of Local Government and Community Affairs",
    category: "ministry",
    description: "Coordinates local government administration, community development, and chieftaincy affairs.",
    location: "Alausa, Ikeja",
    address: "Block 11, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://mlgca.lagosstate.gov.ng",
    officers: [
      { name: "Bolaji Robert", title: "Commissioner for Local Government & Community Affairs", verified: true },
    ],
    block: "Block 11",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-women",
    name: "Ministry of Women Affairs and Poverty Alleviation",
    category: "ministry",
    description: "Promotes gender equality, women empowerment, and poverty reduction programs.",
    location: "Alausa, Ikeja",
    address: "Block 8, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://wapa.lagosstate.gov.ng",
    officers: [
      { name: "Bolaji Dada", title: "Commissioner for Women Affairs & Poverty Alleviation", verified: true },
    ],
    block: "Block 8",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-youth",
    name: "Ministry of Youth and Social Development",
    category: "ministry",
    description: "Develops youth programs, manages social welfare services, and rehabilitation centers.",
    location: "Alausa, Ikeja",
    address: "Block 8, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://youth.lagosstate.gov.ng",
    officers: [
      { name: "Mobolaji Ogunlende", title: "Commissioner for Youth & Social Development", verified: true },
    ],
    block: "Block 8",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-home-affairs",
    name: "Ministry of Home Affairs",
    category: "ministry",
    description: "Manages cultural affairs, religious matters, and community development initiatives.",
    location: "Alausa, Ikeja",
    address: "Block 12, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://homeaffair.lagosstate.gov.ng",
    officers: [
      { name: "Olanrewaju Ibrahim Layode", title: "Commissioner for Home Affairs", verified: true },
    ],
    block: "Block 12",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-establishments",
    name: "Ministry of Establishments, Training and Pensions",
    category: "ministry",
    description: "Manages civil service establishment matters, training programs, and pension administration.",
    location: "Alausa, Ikeja",
    address: "Block 10, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "Afolabi Ayantayo", title: "Commissioner for Establishments, Training & Pensions", verified: true },
    ],
    block: "Block 10",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-special-duties",
    name: "Ministry of Special Duties and Intergovernmental Relations",
    category: "ministry",
    description: "Handles special government assignments and coordinates intergovernmental relations.",
    location: "Alausa, Ikeja",
    address: "Block 9, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    website: "https://specialduties.lagosstate.gov.ng",
    officers: [
      { name: "Gbenga Oyerinde", title: "Commissioner for Special Duties & Intergovernmental Relations", verified: true },
    ],
    block: "Block 9",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "min-tourism",
    name: "Ministry of Tourism, Arts and Culture",
    category: "ministry",
    description: "Develops tourism infrastructure, promotes arts and culture, and manages heritage sites.",
    location: "Alausa, Ikeja",
    address: "Block 7, The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "Toke Benson-Awoyinka", title: "Commissioner for Tourism, Arts and Culture", verified: true },
    ],
    block: "Block 7",
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AGENCIES (12 total — 3 verified, 9 need phone verification)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "lasg-lasepa",
    name: "Lagos State Environmental Protection Agency (LASEPA)",
    category: "agency",
    description: "Responsible for environmental monitoring, pollution control and enforcement of environmental laws.",
    location: "Alausa, Ikeja",
    address: "LASEPA Building, Governor's Road, The Secretariat, Alausa, Lagos",
    phone: "+234-704-635-1295",
    email: "complaint@lasepa.gov.ng",
    website: "https://lasepa.gov.ng",
    officers: [
      { name: "Dr. Dolapo Fasawe", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasaa",
    name: "Lagos State Signage and Advertisement Agency (LASAA)",
    category: "agency",
    description: "Regulates the outdoor advertising industry and signage in Lagos State.",
    location: "Ilupeju, Lagos",
    address: "3B, Town Planning Way, Ilupeju Industrial Scheme, Lagos",
    phone: "+234-1-4510792",
    email: "info@lasaa.gov.ng",
    officers: [
      { name: "Mr. Adedamola Docemo", title: "Managing Director/CEO", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lirs",
    name: "Lagos Internal Revenue Service (LIRS)",
    category: "agency",
    description: "Assesses, collects and accounts for all taxes, levies and revenues due to Lagos State.",
    location: "Alausa, Ikeja",
    address: "Revenue House, 15A, Akintoye Jolaoso Street, Alausa, Ikeja",
    phone: "+234-1-2702208",
    email: "info@lirs.gov.ng",
    website: "https://lirs.gov.ng",
    officers: [
      { name: "Mr. Ayodele Subair", title: "Executive Chairman", verified: false },
      { name: "Mrs. Modupe Ade-Kayode", title: "Director, Tax Operations", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lamata",
    name: "Lagos Metropolitan Area Transport Authority (LAMATA)",
    category: "agency",
    description: "Plans, coordinates and manages transportation in the Lagos metropolitan area including BRT and ferries.",
    location: "Alausa, Ikeja",
    address: "Block C, 2nd Floor, Motorways Centre, 1 Motorways Avenue, Alausa, Ikeja",
    phone: "01-2702778",
    email: "info@lamata-ng.com",
    website: "https://lamata-ng.com",
    officers: [
      { name: "Mr. Abimbola Akinajo", title: "Managing Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasema",
    name: "Lagos State Emergency Management Agency (LASEMA)",
    category: "agency",
    description: "Coordinates emergency response, disaster management and relief operations across Lagos State.",
    location: "Alausa, Ikeja",
    address: "Block 19, State Government Secretariat, Obafemi Awolowo Way, Alausa, Ikeja",
    phone: "8060907333",
    email: "info@lasema.lagosstate.gov.ng",
    website: "https://lasema.lagosstate.gov.ng",
    officers: [
      { name: "Dr. Femi Oke-Osanyintolu", title: "Director General/CEO", verified: true },
    ],
    verified: true,
    needsVerification: false,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasbca",
    name: "Lagos State Building Control Agency (LASBCA)",
    category: "agency",
    description: "Ensures minimum building standards are maintained in construction and renovation of buildings across Lagos.",
    location: "Alausa, Ikeja",
    address: "The Secretariat, Alausa, Ikeja, Lagos",
    phone: "+234-1-4931348",
    email: "info@lasbca.lagosstate.gov.ng",
    website: "https://lasbca.lagosstate.gov.ng",
    officers: [
      { name: "Arc. Gbolahan Owodunni Oki (FNIA)", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-laswa",
    name: "Lagos State Waterways Authority (LASWA)",
    category: "agency",
    description: "Regulates boat and ferry operations, and oversees water transportation safety across Lagos waterways.",
    location: "Lagos Island",
    address: "32, Lawson Street, Onikan, Lagos",
    phone: "+234-1-2700900",
    email: "info@laswa.lagosstate.gov.ng",
    officers: [
      { name: "Ms. Oluwadamilola Emmanuel", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-laspark",
    name: "Lagos State Parks and Gardens Agency (LASPARK)",
    category: "agency",
    description: "Manages public parks, gardens, recreational spaces and open green areas across Lagos.",
    location: "Ikeja",
    address: "Agege Motor Road, Ikeja, Lagos",
    phone: "+234-1-4931250",
    email: "info@laspark.gov.ng",
    officers: [
      { name: "Mrs. Adetoun Popoola", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-taskforce",
    name: "Lagos State Environmental and Special Offences Unit (Task Force)",
    category: "agency",
    description: "Enforces environmental laws and handles special offences including illegal structures and street trading.",
    location: "Alausa, Ikeja",
    address: "The Secretariat, Off Governor's Road, Opposite LASEPA, Obafemi Awolowo Way, Alausa, Ikeja",
    phone: "8033183477",
    email: "info@taskforce.lagosstate.gov.ng",
    website: "https://taskforce.lagosstate.gov.ng",
    officers: [
      { name: "CSP Shola Jejeloye", title: "Chairman", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasiec",
    name: "Lagos State Independent Electoral Commission (LASIEC)",
    category: "agency",
    description: "Organises and conducts local government and chieftaincy elections in Lagos State.",
    location: "Yaba",
    address: "2, Birrel Avenue, Sabo, Yaba, Lagos",
    phone: "08023126327",
    email: "info@lasiec.lagosstate.gov.ng",
    website: "https://lasiec.lagosstate.gov.ng",
    officers: [
      { name: "Justice Candide-Johnson (Rtd)", title: "Chairman", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasiama",
    name: "Lagos State Infrastructure Asset Management Agency (LASIAMA)",
    category: "agency",
    description: "Manages and maintains Lagos State government infrastructure assets for optimal performance.",
    location: "Alausa, Ikeja",
    address: "Lagos State Government Secretariat, Alausa, Ikeja, Lagos",
    phone: "+234-1-7630000",
    email: "info@lasiama.lagosstate.gov.ng",
    website: "https://lasiama.lagosstate.gov.ng",
    officers: [
      { name: "Engr. Aramide Adeyoye", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasimra",
    name: "Lagos State Infrastructure Maintenance and Regulatory Agency (LASIMRA)",
    category: "agency",
    description: "Regulates utility infrastructure including oil, gas, telecommunications and electricity companies in Lagos.",
    location: "Agidingbi, Ikeja",
    address: "2 Yusuf Close, Off Bayo Ajayi Street, Agidingbi Phase 2, Ikeja",
    phone: "+234-1-4931300",
    email: "info@lasimra.gov.ng",
    website: "https://lasimra.gov.ng",
    officers: [
      { name: "Mrs. Bisoye Coker-Odusote", title: "General Manager/CEO", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lastma",
    name: "Lagos State Traffic Management Authority (LASTMA)",
    category: "agency",
    description: "Manages traffic flow, enforces traffic laws, and reduces congestion in Lagos State.",
    location: "Oshodi, Lagos",
    address: "LASTMA Headquarters, Oshodi, Lagos",
    phone: "112, 767",
    email: "",
    officers: [
      { name: "", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lnsa",
    name: "Lagos State Neighbourhood Safety Agency (LNSA)",
    category: "agency",
    description: "Provides community policing, neighbourhood watch, and local security services.",
    location: "Alausa, Ikeja",
    address: "The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "", title: "Commandant-General", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasppa",
    name: "Lagos State Public Procurement Agency (LASPPA)",
    category: "agency",
    description: "Regulates public procurement processes and ensures transparency in government contracts.",
    location: "Alausa, Ikeja",
    address: "The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "", title: "Director-General", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PARASTATALS (13 total — 0 verified, all need phone verification)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "lasg-lawma",
    name: "Lagos State Waste Management Authority (LAWMA)",
    category: "parastatal",
    description: "Manages solid waste collection, disposal and recycling services across Lagos State.",
    location: "Ojota",
    address: "LAWMA Headquarters, Along Lagos-Ibadan Expressway, Ojota, Lagos",
    phone: "+234-1-4930022",
    email: "info@lawma.gov.ng",
    website: "https://lawma.gov.ng",
    officers: [
      { name: "Mr. Ibrahim Odumboni", title: "Managing Director", verified: false },
      { name: "Mrs. Toyin Oke", title: "Executive Director, Operations", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasu",
    name: "Lagos State University (LASU)",
    category: "parastatal",
    description: "State-owned university providing tertiary education in science, arts, law and management sciences.",
    location: "Ojo",
    address: "LASU Main Campus, Badagry Expressway, Ojo, Lagos",
    phone: "+234-1-7740000",
    email: "registrar@lasu.edu.ng",
    website: "https://lasu.edu.ng",
    officers: [
      { name: "Prof. Ibiyemi Olatunji-Bello", title: "Vice Chancellor", verified: false },
      { name: "Mr. Emmanuel Fabunmi", title: "Registrar", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lasuth",
    name: "Lagos State University Teaching Hospital (LASUTH)",
    category: "parastatal",
    description: "Premier state-owned teaching hospital providing specialist health care and medical training in Lagos.",
    location: "Ikeja",
    address: "1-5, Oba Akinjobi Road, Ikeja GRA, Lagos",
    phone: "+234-1-2793800",
    email: "info@lasuth.gov.ng",
    officers: [
      { name: "Prof. Adetokunbo Fabamwo", title: "Chief Medical Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lagis",
    name: "Lagos State Geographic Information Systems (LAGIS)",
    category: "parastatal",
    description: "Manages geographic data, land registration, mapping and GIS services for Lagos State.",
    location: "Alausa, Ikeja",
    address: "Land Bureau Complex, Alausa Secretariat, Ikeja, Lagos",
    phone: "+234-1-4939000",
    email: "info@lagis.gov.ng",
    officers: [
      { name: "Mr. Olajide Babatunde", title: "Director General", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lspwc",
    name: "Lagos State Public Works Corporation (LSPWC)",
    category: "parastatal",
    description: "Executes public works projects, road maintenance and infrastructure construction for Lagos State.",
    location: "Isheri, Ojodu",
    address: "Works Road, Ojodu-Berger, Isheri, Lagos",
    phone: "+234-1-7630000",
    email: "info@lspwc-ng.com",
    website: "https://lspwc-ng.com",
    officers: [
      { name: "Engr. Aramide Adeyoye", title: "Managing Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lstf",
    name: "Lagos State Security Trust Fund (LSSTF)",
    category: "parastatal",
    description: "Mobilises resources to support and equip security agencies for improved safety in Lagos State.",
    location: "Lagos Island",
    address: "Lagos State Secretariat, Alausa, Ikeja, Lagos",
    phone: "+234-1-7630000",
    email: "info@lagosstatesecuritytrustfund.org",
    website: "https://lagosstatesecuritytrustfund.org",
    officers: [
      { name: "Mr. Rasaq Balogun", title: "Executive Secretary", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lbic",
    name: "Lagos State Building Investment Corporation (LBIC)",
    category: "parastatal",
    description: "Develops and manages real estate investments and affordable housing on behalf of Lagos State.",
    location: "Ebute Metta",
    address: "3, Borno Way, Ebute Metta, Lagos",
    phone: "+234-1-5850001",
    email: "info@lbic.gov.ng",
    officers: [
      { name: "Arc. Gbolahan Lawal", title: "Managing Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-ferry",
    name: "Lagos State Ferry Services Corporation",
    category: "parastatal",
    description: "Provides affordable and reliable ferry passenger services across Lagos waterways.",
    location: "Onikan, Lagos Island",
    address: "32, Lawson Street, Onikan, Lagos",
    phone: "+234-1-2700800",
    email: "info@ferryservices.lagosstate.gov.ng",
    website: "https://ferryservices.lagosstate.gov.ng",
    officers: [
      { name: "Mr. Kehinde Osinaike", title: "Managing Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-radio-lagos",
    name: "Radio Lagos",
    category: "parastatal",
    description: "State-owned public broadcaster providing news, information and entertainment to Lagos residents.",
    location: "Agidingbi, Ikeja",
    address: "2A, Lateef Jakande Road, Agidingbi, Ikeja, Lagos",
    phone: "234-1-4960568",
    email: "info@radio.org.ng",
    website: "https://radio.org.ng/lagos",
    officers: [
      { name: "Mr. Tokunbo Adebisi", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-ekofm",
    name: "Eko FM",
    category: "parastatal",
    description: "Lagos State Government FM radio station broadcasting music, culture and current affairs content.",
    location: "Agidingbi, Ikeja",
    address: "Lateef Jakande Road, Agidingbi, Ikeja, Lagos",
    phone: "014960568",
    email: "info@ekofm.lagosstate.gov.ng",
    website: "https://ekofm.lagosstate.gov.ng",
    officers: [
      { name: "Mrs. Bidemi Zakariyau", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-exam-board",
    name: "Lagos State Examinations Board (LSEB)",
    category: "parastatal",
    description: "Conducts secondary school examinations and manages standardised testing for Lagos State students.",
    location: "Agege",
    address: "254, Ipaja Road, Near Mulero Bus Stop, Agege, Lagos",
    phone: "08023548336",
    email: "info@examboard.lagosstate.gov.ng",
    website: "https://examboard.lagosstate.gov.ng",
    officers: [
      { name: "Mrs. Abiodun Adewale", title: "Registrar", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-arts-culture",
    name: "Lagos State Council for Arts and Culture",
    category: "parastatal",
    description: "Promotes, preserves and develops arts, culture and creative industries across Lagos State.",
    location: "Ikeja",
    address: "133, Obafemi Awolowo Way, Ikeja, Lagos",
    phone: "09099155485",
    email: "info@artandculture.lagosstate.gov.ng",
    website: "https://artandculture.lagosstate.gov.ng",
    officers: [
      { name: "Mr. Makinde Adeniran", title: "Executive Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-litf",
    name: "Lagos International Trade Fair Complex Management Board",
    category: "parastatal",
    description: "Manages and operates the Lagos International Trade Fair Complex to promote commerce and industry.",
    location: "Abule Osun, Lagos",
    address: "Lagos-Badagry Expressway, Abule Osun, Lagos",
    phone: "+234-1-5890797",
    email: "info@litf.gov.ng",
    officers: [
      { name: "Mr. Rezak Abiodun Balogun", title: "General Manager", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lwc",
    name: "Lagos State Water Corporation",
    category: "parastatal",
    description: "Provides potable water supply and manages water distribution infrastructure.",
    location: "Iju",
    address: "Iju Water Works, Iju, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "", title: "Managing Director", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-lsdpc",
    name: "Lagos State Development and Property Corporation (LSDPC)",
    category: "parastatal",
    description: "Develops and manages state-owned properties and housing estates.",
    location: "Alausa, Ikeja",
    address: "The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "", title: "Managing Director/CEO", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-health-commission",
    name: "Lagos State Health Service Commission",
    category: "parastatal",
    description: "Manages health personnel, hospital administration, and health service delivery.",
    location: "Alausa, Ikeja",
    address: "The Secretariat, Alausa, Ikeja, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "", title: "Chairman", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
  {
    id: "lasg-sports",
    name: "Lagos State Sports Commission",
    category: "parastatal",
    description: "Promotes sports development, manages sports facilities, and organizes sporting events.",
    location: "Surulere",
    address: "Teslim Balogun Stadium, Surulere, Lagos",
    phone: "",
    email: "",
    officers: [
      { name: "", title: "Chairman", verified: false },
    ],
    verified: false,
    needsVerification: true,
    lastUpdated: "2026-07-18",
  },
];

export const getByCategory = (category: Entity["category"]) =>
  entities.filter((e) => e.category === category);

export const getById = (id: string) => entities.find((e) => e.id === id);

export const searchEntities = (query: string) => {
  const q = query.toLowerCase();
  return entities.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.location.toLowerCase().includes(q) ||
      e.officers.some((o) => o.name.toLowerCase().includes(q))
  );
};

export const getVerifiedCount = () => entities.filter((e) => e.verified).length;
export const getNeedsVerificationCount = () => entities.filter((e) => e.needsVerification).length;
export const getTotalCount = () => entities.length;
