export type Ward = {
  id: string;
  name: string;
  description?: string;
};

export type LCDA = {
  id: string;
  name: string;
  parentLgaId: string;
  parentLgaName: string;
  chairman: string;
  viceChairman?: string;
  address: string;
  phone: string;
  email?: string;
  zone: "Island" | "Mainland" | "Suburban";
  established: string;
  headquarters: string;
  population?: string;
  area?: string;
  coordinates: { lat: number; lng: number };
  bio: string;
  knownFor: string[];
  wards: Ward[];
};

export const lcdas: LCDA[] = [

  // ── AGEGE LGA ─────────────────────────────────────────────────────────────

  {
    id: "agege-lcda",
    name: "Agege LCDA",
    parentLgaId: "agege",
    parentLgaName: "Agege",
    chairman: "Hon. Seun Adeyemi",
    address: "Agege LCDA Secretariat, Old Abeokuta Road, Agege, Lagos",
    phone: "+234-1-4930110",
    email: "info@agege-lcda.lagosstate.gov.ng",
    zone: "Mainland",
    established: "2002",
    headquarters: "Agege",
    population: "245,000",
    area: "12 km²",
    coordinates: { lat: 6.6193, lng: 3.3192 },
    bio: "Agege LCDA covers the core Agege township, one of the most densely populated council areas in Lagos. It is a major hub for the textile trade, garment manufacturing and street food culture. The area has a deeply rooted Muslim and Christian population living harmoniously.",
    knownFor: ["Textile & garment trade", "Agege bread", "Pen Cinema", "Dense urban market"],
    wards: [
      { id: "agege-lcda-w1", name: "Ward A1 — Dopemu / Agege Central", description: "Covers Dopemu junction and central Agege market area." },
      { id: "agege-lcda-w2", name: "Ward A2 — Agege Station", description: "Railway station community and surrounding commercial streets." },
      { id: "agege-lcda-w3", name: "Ward A3 — Pen Cinema", description: "The Pen Cinema roundabout area and adjacent residential zones." },
      { id: "agege-lcda-w4", name: "Ward A4 — Oko-Oba", description: "Oko-Oba community stretching toward Abattoir." },
      { id: "agege-lcda-w5", name: "Ward A5 — Abattoir / Mangoro", description: "Abattoir and Mangoro residential and light commercial areas." },
      { id: "agege-lcda-w6", name: "Ward A6 — Command", description: "Command area and military-adjacent communities." },
    ],
  },
  {
    id: "orile-agege-lcda",
    name: "Orile-Agege LCDA",
    parentLgaId: "agege",
    parentLgaName: "Agege",
    chairman: "Hon. Kazeem Adewale",
    address: "Orile-Agege LCDA Secretariat, Agege, Lagos",
    phone: "+234-1-4930120",
    zone: "Mainland",
    established: "2002",
    headquarters: "Orile-Agege",
    population: "215,000",
    area: "10 km²",
    coordinates: { lat: 6.6100, lng: 3.3050 },
    bio: "Orile-Agege LCDA serves the southwestern portion of the old Agege LGA. The area is characterised by a mix of residential estates and informal settlements with strong community associations and youth groups.",
    knownFor: ["Residential communities", "Light industry", "Community associations"],
    wards: [
      { id: "orile-agege-w1", name: "Ward B1 — Oke-Koto", description: "Oke-Koto residential district." },
      { id: "orile-agege-w2", name: "Ward B2 — Onipetesi", description: "Onipetesi area and adjoining streets." },
      { id: "orile-agege-w3", name: "Ward B3 — Ijaiye / Orile", description: "Ijaiye-Orile community area." },
      { id: "orile-agege-w4", name: "Ward B4 — Oyewole", description: "Oyewole district and surrounding neighbourhood." },
      { id: "orile-agege-w5", name: "Ward B5 — Tabon-Tabon", description: "Tabon-Tabon area toward Agege boundary." },
    ],
  },

  // ── AJEROMI-IFELODUN LGA ──────────────────────────────────────────────────

  {
    id: "ajeromi-lcda",
    name: "Ajeromi LCDA",
    parentLgaId: "ajeromi-ifelodun",
    parentLgaName: "Ajeromi-Ifelodun",
    chairman: "Hon. Bola Nwachukwu",
    address: "Ajeromi LCDA Secretariat, Ajegunle, Lagos",
    phone: "+234-1-4930210",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ajegunle",
    population: "380,000",
    area: "10 km²",
    coordinates: { lat: 6.4698, lng: 3.3541 },
    bio: "Ajeromi LCDA covers the core Ajegunle district — one of the most densely populated urban communities in West Africa. Despite infrastructural challenges, the area is famous for producing world-class musicians, athletes and entrepreneurs.",
    knownFor: ["Music culture", "Boxing", "Wharf Road", "Urban resilience"],
    wards: [
      { id: "ajeromi-w1", name: "Ward 1 — Ajegunle Central", description: "Heart of Ajegunle community." },
      { id: "ajeromi-w2", name: "Ward 2 — Tolu", description: "Tolu village and waterfront area." },
      { id: "ajeromi-w3", name: "Ward 3 — Layeni", description: "Layeni district residential area." },
      { id: "ajeromi-w4", name: "Ward 4 — Olodi Apapa", description: "Olodi Apapa community." },
      { id: "ajeromi-w5", name: "Ward 5 — Amukoko", description: "Amukoko residential area toward Apapa." },
    ],
  },
  {
    id: "ifelodun-lcda",
    name: "Ifelodun LCDA",
    parentLgaId: "ajeromi-ifelodun",
    parentLgaName: "Ajeromi-Ifelodun",
    chairman: "Hon. Wasiu Ogunbayo",
    address: "Ifelodun LCDA Secretariat, Ajeromi, Lagos",
    phone: "+234-1-4930220",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ifelodun",
    coordinates: { lat: 6.4600, lng: 3.3400 },
    bio: "Ifelodun LCDA covers the eastern section of the Ajeromi-Ifelodun LGA bordering Apapa. The area has significant fishing and market communities.",
    knownFor: ["Fishing communities", "Market trade", "Waterfront access"],
    wards: [
      { id: "ifelodun-w1", name: "Ward 1 — Ifelodun Central", description: "Central Ifelodun administrative area." },
      { id: "ifelodun-w2", name: "Ward 2 — Boundary", description: "Boundary area near Apapa." },
      { id: "ifelodun-w3", name: "Ward 3 — Alakara", description: "Alakara community district." },
      { id: "ifelodun-w4", name: "Ward 4 — Ago-Okota", description: "Ago-Okota residential area." },
      { id: "ifelodun-w5", name: "Ward 5 — Owutu", description: "Owutu waterfront community." },
    ],
  },

  // ── ALIMOSHO LGA ──────────────────────────────────────────────────────────

  {
    id: "egbe-idimu-lcda",
    name: "Egbe-Idimu LCDA",
    parentLgaId: "alimosho",
    parentLgaName: "Alimosho",
    chairman: "Hon. Ganiyu Kola-Daisi",
    address: "Egbe-Idimu LCDA Secretariat, Egbe, Lagos",
    phone: "+234-1-4930310",
    zone: "Suburban",
    established: "2002",
    headquarters: "Egbe",
    population: "220,000",
    area: "35 km²",
    coordinates: { lat: 6.5700, lng: 3.2900 },
    bio: "Egbe-Idimu LCDA is a fast-growing residential council area covering Egbe and Idimu communities. It has experienced significant real estate development and has good road connectivity to the Lagos-Ibadan Expressway.",
    knownFor: ["Residential estates", "Egbe Market", "Church communities"],
    wards: [
      { id: "egbe-idimu-w1", name: "Ward 1 — Egbe Central", description: "Egbe town centre and market area." },
      { id: "egbe-idimu-w2", name: "Ward 2 — Idimu", description: "Idimu residential community." },
      { id: "egbe-idimu-w3", name: "Ward 3 — Isheri-Olofin", description: "Isheri-Olofin border community." },
      { id: "egbe-idimu-w4", name: "Ward 4 — Iyana-Isashi", description: "Iyana-Isashi neighbourhood." },
      { id: "egbe-idimu-w5", name: "Ward 5 — Ago Palace Way", description: "Ago Palace Way corridor." },
    ],
  },
  {
    id: "igando-ikotun-lcda",
    name: "Igando-Ikotun LCDA",
    parentLgaId: "alimosho",
    parentLgaName: "Alimosho",
    chairman: "Hon. Moshood Adekunle",
    address: "Igando-Ikotun LCDA Secretariat, Igando, Lagos",
    phone: "+234-1-4930320",
    zone: "Suburban",
    established: "2002",
    headquarters: "Igando",
    coordinates: { lat: 6.5600, lng: 3.2600 },
    bio: "Igando-Ikotun LCDA covers the Igando and Ikotun communities, major residential and commercial areas in the Alimosho axis. Igando Market is one of the largest in the area.",
    knownFor: ["Igando Market", "Residential estates", "Community trade"],
    wards: [
      { id: "igando-ikotun-w1", name: "Ward 1 — Igando", description: "Igando central community." },
      { id: "igando-ikotun-w2", name: "Ward 2 — Ikotun", description: "Ikotun township area." },
      { id: "igando-ikotun-w3", name: "Ward 3 — Isheri-Igando", description: "Isheri-Igando border area." },
      { id: "igando-ikotun-w4", name: "Ward 4 — Abaranje", description: "Abaranje residential community." },
      { id: "igando-ikotun-w5", name: "Ward 5 — Ayobo", description: "Ayobo township community." },
    ],
  },
  {
    id: "ikotun-igando-lcda",
    name: "Ikotun-Igando LCDA",
    parentLgaId: "alimosho",
    parentLgaName: "Alimosho",
    chairman: "Hon. Segun Olatunbosun",
    address: "Ikotun-Igando LCDA Secretariat, Ikotun, Lagos",
    phone: "+234-1-4930330",
    zone: "Suburban",
    established: "2002",
    headquarters: "Ikotun",
    coordinates: { lat: 6.5500, lng: 3.2500 },
    bio: "Ikotun-Igando LCDA is a twin council area serving the densely settled Ikotun-Igando corridor. The area has vibrant street markets and growing infrastructure.",
    knownFor: ["Street markets", "Residential growth", "Transport corridor"],
    wards: [
      { id: "ikotun-igando-w1", name: "Ward 1 — Ikotun Central", description: "Ikotun town central area." },
      { id: "ikotun-igando-w2", name: "Ward 2 — Idimu Road", description: "Idimu Road residential stretch." },
      { id: "ikotun-igando-w3", name: "Ward 3 — Ile-Epo", description: "Ile-Epo housing estate area." },
      { id: "ikotun-igando-w4", name: "Ward 4 — Ijegun", description: "Ijegun community." },
      { id: "ikotun-igando-w5", name: "Ward 5 — Iyana-Ipaja", description: "Iyana-Ipaja junction community." },
    ],
  },
  {
    id: "isolo-lcda",
    name: "Isolo LCDA",
    parentLgaId: "alimosho",
    parentLgaName: "Alimosho",
    chairman: "Hon. Tunde Bello",
    address: "Isolo LCDA Secretariat, Isolo, Lagos",
    phone: "+234-1-4930340",
    zone: "Suburban",
    established: "2002",
    headquarters: "Isolo",
    coordinates: { lat: 6.5354, lng: 3.3000 },
    bio: "Isolo LCDA is a major industrial and residential council area. It hosts Isolo Industrial Estate, one of the oldest in Lagos, alongside large residential communities along Oshodi-Apapa Expressway.",
    knownFor: ["Isolo Industrial Estate", "Manufacturing hub", "Residential estates"],
    wards: [
      { id: "isolo-w1", name: "Ward 1 — Isolo Central", description: "Isolo town centre and market." },
      { id: "isolo-w2", name: "Ward 2 — Ago-Palace", description: "Ago-Palace residential area." },
      { id: "isolo-w3", name: "Ward 3 — Ilasamaja", description: "Ilasamaja community." },
      { id: "isolo-w4", name: "Ward 4 — Okota", description: "Okota residential district." },
      { id: "isolo-w5", name: "Ward 5 — Cele / Expressway", description: "Cele bus stop and expressway area." },
    ],
  },
  {
    id: "mosan-okunola-lcda",
    name: "Mosan-Okunola LCDA",
    parentLgaId: "alimosho",
    parentLgaName: "Alimosho",
    chairman: "Hon. Bolaji Sanusi",
    address: "Mosan-Okunola LCDA Secretariat, Ipaja, Lagos",
    phone: "+234-1-4930350",
    zone: "Suburban",
    established: "2002",
    headquarters: "Ipaja",
    coordinates: { lat: 6.6100, lng: 3.2300 },
    bio: "Mosan-Okunola LCDA covers the Ipaja, Mosan and Okunola communities in the far western part of Alimosho. The area borders Ogun State and has a large commuter population.",
    knownFor: ["Ipaja Road corridor", "Border communities", "Commuter hub"],
    wards: [
      { id: "mosan-okunola-w1", name: "Ward 1 — Ipaja Central", description: "Ipaja town centre." },
      { id: "mosan-okunola-w2", name: "Ward 2 — Mosan", description: "Mosan community area." },
      { id: "mosan-okunola-w3", name: "Ward 3 — Okunola", description: "Okunola residential district." },
      { id: "mosan-okunola-w4", name: "Ward 4 — Akowonjo", description: "Akowonjo roundabout area." },
      { id: "mosan-okunola-w5", name: "Ward 5 — Meiran", description: "Meiran border community." },
    ],
  },

  // ── AMUWO-ODOFIN LGA ──────────────────────────────────────────────────────

  {
    id: "amuwo-odofin-lcda",
    name: "Amuwo-Odofin LCDA",
    parentLgaId: "amuwo-odofin",
    parentLgaName: "Amuwo-Odofin",
    chairman: "Hon. Adeola Ogunyemi",
    address: "Amuwo-Odofin LCDA Secretariat, Mile 2, Lagos",
    phone: "+234-1-4930410",
    zone: "Mainland",
    established: "2002",
    headquarters: "Mile 2",
    coordinates: { lat: 6.4728, lng: 3.2944 },
    bio: "Amuwo-Odofin LCDA covers the northern part of the LGA including Mile 2, Ojo Barracks and the International Trade Fair Complex vicinity. It is a key transport hub connecting Lagos Island and the Mainland.",
    knownFor: ["Mile 2 transport hub", "Trade Fair proximity", "Military barracks"],
    wards: [
      { id: "amuwo-odofin-w1", name: "Ward 1 — Mile 2", description: "Mile 2 commercial and transport area." },
      { id: "amuwo-odofin-w2", name: "Ward 2 — Festac Town Phase 1", description: "Festac Town first phase residential area." },
      { id: "amuwo-odofin-w3", name: "Ward 3 — Festac Town Phase 2", description: "Festac Town second phase residential area." },
      { id: "amuwo-odofin-w4", name: "Ward 4 — Ojo Barracks", description: "Military barracks and adjacent community." },
      { id: "amuwo-odofin-w5", name: "Ward 5 — Trade Fair", description: "International Trade Fair Complex area." },
    ],
  },
  {
    id: "oriade-lcda",
    name: "Oriade LCDA",
    parentLgaId: "amuwo-odofin",
    parentLgaName: "Amuwo-Odofin",
    chairman: "Hon. Adewale Adisa",
    address: "Oriade LCDA Secretariat, Satellite Town, Lagos",
    phone: "+234-1-4930420",
    zone: "Mainland",
    established: "2002",
    headquarters: "Satellite Town",
    coordinates: { lat: 6.4500, lng: 3.2700 },
    bio: "Oriade LCDA covers Satellite Town and surrounding communities in the southern part of Amuwo-Odofin. The area has well-planned residential estates and petrochemical industry proximity.",
    knownFor: ["Satellite Town estates", "Planned residential areas", "Atlas Cove proximity"],
    wards: [
      { id: "oriade-w1", name: "Ward 1 — Satellite Town A", description: "Northern section of Satellite Town." },
      { id: "oriade-w2", name: "Ward 2 — Satellite Town B", description: "Southern section of Satellite Town." },
      { id: "oriade-w3", name: "Ward 3 — Alakija", description: "Alakija residential community." },
      { id: "oriade-w4", name: "Ward 4 — Kirikiri", description: "Kirikiri industrial and residential area." },
      { id: "oriade-w5", name: "Ward 5 — Tolu / Oriade", description: "Tolu and Oriade communities." },
    ],
  },

  // ── APAPA LGA ─────────────────────────────────────────────────────────────

  {
    id: "apapa-iganmu-lcda",
    name: "Apapa-Iganmu LCDA",
    parentLgaId: "apapa",
    parentLgaName: "Apapa",
    chairman: "Hon. Seun Ogunbanjo",
    address: "Apapa-Iganmu LCDA Secretariat, Apapa, Lagos",
    phone: "+234-1-4930510",
    zone: "Mainland",
    established: "2002",
    headquarters: "Apapa",
    coordinates: { lat: 6.4481, lng: 3.3591 },
    bio: "Apapa-Iganmu LCDA covers the port district and Iganmu community. It sits at the heart of Nigeria's maritime commerce, with the Apapa and Tin Can Island ports within its jurisdiction.",
    knownFor: ["Port activities", "Iganmu industrial area", "Maritime trade", "Apapa GRA"],
    wards: [
      { id: "apapa-iganmu-w1", name: "Ward 1 — Apapa Central", description: "Apapa commercial and port district." },
      { id: "apapa-iganmu-w2", name: "Ward 2 — GRA", description: "Apapa Government Reserved Area." },
      { id: "apapa-iganmu-w3", name: "Ward 3 — Iganmu", description: "Iganmu residential and industrial area." },
      { id: "apapa-iganmu-w4", name: "Ward 4 — Tin Can", description: "Tin Can Island port area." },
      { id: "apapa-iganmu-w5", name: "Ward 5 — Ijora", description: "Ijora community near causeway." },
      { id: "apapa-iganmu-w6", name: "Ward 6 — Sari-Iganmu", description: "Sari-Iganmu residential community." },
    ],
  },

  // ── BADAGRY LGA ───────────────────────────────────────────────────────────

  {
    id: "badagry-east-lcda",
    name: "Badagry East LCDA",
    parentLgaId: "badagry",
    parentLgaName: "Badagry",
    chairman: "Hon. Gafar Fadipe",
    address: "Badagry East LCDA Secretariat, Badagry, Lagos",
    phone: "+234-1-4930610",
    zone: "Suburban",
    established: "2002",
    headquarters: "Badagry",
    coordinates: { lat: 6.4154, lng: 2.9100 },
    bio: "Badagry East LCDA covers the eastern portion of the historic Badagry town including the slave heritage sites and coastal fishing communities.",
    knownFor: ["Slave trade heritage", "Coastal fishing", "Heritage tourism"],
    wards: [
      { id: "badagry-east-w1", name: "Ward 1 — Badagry Central", description: "Historic Badagry town centre." },
      { id: "badagry-east-w2", name: "Ward 2 — Awhanjigo", description: "Awhanjigo waterfront community." },
      { id: "badagry-east-w3", name: "Ward 3 — Gberefu", description: "Gberefu Island and beach area." },
      { id: "badagry-east-w4", name: "Ward 4 — Ajido", description: "Ajido fishing community." },
      { id: "badagry-east-w5", name: "Ward 5 — Posukoh", description: "Posukoh lagoon community." },
    ],
  },
  {
    id: "badagry-west-lcda",
    name: "Badagry West LCDA",
    parentLgaId: "badagry",
    parentLgaName: "Badagry",
    chairman: "Hon. Michael Olawale",
    address: "Badagry West LCDA Secretariat, Seme, Lagos",
    phone: "+234-1-4930620",
    zone: "Suburban",
    established: "2002",
    headquarters: "Seme",
    coordinates: { lat: 6.3500, lng: 2.7200 },
    bio: "Badagry West LCDA covers the border communities toward the Republic of Benin, including the Seme border crossing. It has a significant cross-border trade economy.",
    knownFor: ["Seme border crossing", "Cross-border trade", "Border communities"],
    wards: [
      { id: "badagry-west-w1", name: "Ward 1 — Seme Border", description: "Nigeria-Benin Republic border crossing area." },
      { id: "badagry-west-w2", name: "Ward 2 — Kweme", description: "Kweme community near the border." },
      { id: "badagry-west-w3", name: "Ward 3 — Gayingbo", description: "Gayingbo fishing and farming community." },
      { id: "badagry-west-w4", name: "Ward 4 — Badagry Creek", description: "Creek-side communities." },
      { id: "badagry-west-w5", name: "Ward 5 — Agara", description: "Agara village area." },
    ],
  },

  // ── EPE LGA ───────────────────────────────────────────────────────────────

  {
    id: "epe-lcda",
    name: "Epe LCDA",
    parentLgaId: "epe",
    parentLgaName: "Epe",
    chairman: "Hon. Bolaji Makinde",
    address: "Epe LCDA Secretariat, Epe, Lagos",
    phone: "+234-1-4930710",
    zone: "Suburban",
    established: "2002",
    headquarters: "Epe",
    coordinates: { lat: 6.5864, lng: 3.9779 },
    bio: "Epe LCDA covers the historic Epe town on the Lekki Lagoon. The area is known for fishing, the Ojude Oba festival and its growing status as a gateway to the Lekki Free Zone.",
    knownFor: ["Epe Fish Market", "Ojude Oba Festival", "Lagoon fishing", "Emerging smart city"],
    wards: [
      { id: "epe-w1", name: "Ward 1 — Epe Central", description: "Epe town centre and royal palace area." },
      { id: "epe-w2", name: "Ward 2 — Marina / Waterfront", description: "Epe marina and lagoon waterfront." },
      { id: "epe-w3", name: "Ward 3 — Odo-Epe", description: "Odo-Epe riverside community." },
      { id: "epe-w4", name: "Ward 4 — Poka", description: "Poka village and farming area." },
      { id: "epe-w5", name: "Ward 5 — Eredo", description: "Eredo community and ancient earthworks area." },
    ],
  },
  {
    id: "ikosi-ejinrin-lcda",
    name: "Ikosi-Ejinrin LCDA",
    parentLgaId: "epe",
    parentLgaName: "Epe",
    chairman: "Hon. Saheed Afolabi",
    address: "Ikosi-Ejinrin LCDA Secretariat, Ejinrin, Lagos",
    phone: "+234-1-4930720",
    zone: "Suburban",
    established: "2002",
    headquarters: "Ejinrin",
    coordinates: { lat: 6.5300, lng: 3.8500 },
    bio: "Ikosi-Ejinrin LCDA covers the Ejinrin and Ikosi communities on the Lagos-Epe Expressway corridor. The area has significant agricultural and fishing activity.",
    knownFor: ["Agricultural communities", "Lagos-Epe corridor", "Fishing lagoon communities"],
    wards: [
      { id: "ikosi-ejinrin-w1", name: "Ward 1 — Ejinrin", description: "Ejinrin town and market." },
      { id: "ikosi-ejinrin-w2", name: "Ward 2 — Ikosi", description: "Ikosi village community." },
      { id: "ikosi-ejinrin-w3", name: "Ward 3 — Ketu-Epe", description: "Ketu-Epe riverside community." },
      { id: "ikosi-ejinrin-w4", name: "Ward 4 — Agbowa", description: "Agbowa farming community." },
      { id: "ikosi-ejinrin-w5", name: "Ward 5 — Itoikin", description: "Itoikin lagoon-side community." },
    ],
  },

  // ── ETI-OSA LGA ───────────────────────────────────────────────────────────

  {
    id: "ikoyi-obalende-lcda",
    name: "Ikoyi-Obalende LCDA",
    parentLgaId: "eti-osa",
    parentLgaName: "Eti-Osa",
    chairman: "Hon. Ade Adewale",
    address: "Ikoyi-Obalende LCDA Secretariat, Ikoyi, Lagos",
    phone: "+234-1-4930810",
    zone: "Island",
    established: "2002",
    headquarters: "Ikoyi",
    coordinates: { lat: 6.4530, lng: 3.4280 },
    bio: "Ikoyi-Obalende LCDA covers two of Lagos's most iconic neighbourhoods. Ikoyi is one of Nigeria's most exclusive residential and diplomatic enclaves while Obalende is a major transport interchange connecting Lagos Island to the Mainland.",
    knownFor: ["Luxury residences", "Diplomatic quarters", "Obalende bus terminal", "Falomo Bridge"],
    wards: [
      { id: "ikoyi-obalende-w1", name: "Ward 1 — Ikoyi North", description: "Northern Ikoyi exclusive residential area." },
      { id: "ikoyi-obalende-w2", name: "Ward 2 — Ikoyi South", description: "Southern Ikoyi and Parkview Estate." },
      { id: "ikoyi-obalende-w3", name: "Ward 3 — Obalende", description: "Obalende transport hub and community." },
      { id: "ikoyi-obalende-w4", name: "Ward 4 — Five Cowries", description: "Five Cowries Creek waterfront area." },
      { id: "ikoyi-obalende-w5", name: "Ward 5 — Awolowo Road", description: "Awolowo Road commercial and diplomatic corridor." },
    ],
  },
  {
    id: "iru-victoria-island-lcda",
    name: "Iru-Victoria Island LCDA",
    parentLgaId: "eti-osa",
    parentLgaName: "Eti-Osa",
    chairman: "Hon. Kayode Fashola",
    address: "Iru-Victoria Island LCDA Secretariat, Victoria Island, Lagos",
    phone: "+234-1-4930820",
    zone: "Island",
    established: "2002",
    headquarters: "Victoria Island",
    coordinates: { lat: 6.4281, lng: 3.4219 },
    bio: "Iru-Victoria Island LCDA covers Victoria Island — Nigeria's premier business and entertainment district. Home to multinational corporations, five-star hotels, embassies and the Eko Atlantic City development.",
    knownFor: ["Multinational HQs", "Eko Atlantic City", "Fine dining", "Bar Beach", "Embassies"],
    wards: [
      { id: "iru-vi-w1", name: "Ward 1 — Victoria Island A", description: "Northern Victoria Island commercial district." },
      { id: "iru-vi-w2", name: "Ward 2 — Victoria Island B", description: "Southern Victoria Island and beachfront." },
      { id: "iru-vi-w3", name: "Ward 3 — Eko Atlantic", description: "Eko Atlantic City reclaimed land development." },
      { id: "iru-vi-w4", name: "Ward 4 — Oniru", description: "Oniru Royal Estate and beachfront." },
      { id: "iru-vi-w5", name: "Ward 5 — Kuramo", description: "Kuramo Waters and Bar Beach area." },
    ],
  },
  {
    id: "lagos-island-east-lcda",
    name: "Lagos Island East LCDA",
    parentLgaId: "eti-osa",
    parentLgaName: "Eti-Osa",
    chairman: "Hon. Tunde Dosunmu",
    address: "Lagos Island East LCDA Secretariat, Lekki, Lagos",
    phone: "+234-1-4930830",
    zone: "Island",
    established: "2002",
    headquarters: "Lekki Phase 1",
    coordinates: { lat: 6.4350, lng: 3.4750 },
    bio: "Lagos Island East LCDA covers Lekki Phase 1 and its surroundings — one of the fastest-growing luxury residential and commercial areas in Lagos, with renowned restaurants, art galleries and tech offices.",
    knownFor: ["Lekki Phase 1", "Nike Art Gallery", "Upscale dining", "Tech offices"],
    wards: [
      { id: "li-east-w1", name: "Ward 1 — Lekki Phase 1 A", description: "Northern Lekki Phase 1 residential area." },
      { id: "li-east-w2", name: "Ward 2 — Lekki Phase 1 B", description: "Southern Lekki Phase 1 area." },
      { id: "li-east-w3", name: "Ward 3 — Marwa / Chevron", description: "Marwa roundabout and Chevron Drive corridor." },
      { id: "li-east-w4", name: "Ward 4 — Jakande", description: "Jakande roundabout area." },
      { id: "li-east-w5", name: "Ward 5 — Osapa London", description: "Osapa London estate area." },
    ],
  },

  // ── IBEJU-LEKKI LGA ───────────────────────────────────────────────────────

  {
    id: "ibeju-lcda",
    name: "Ibeju LCDA",
    parentLgaId: "ibeju-lekki",
    parentLgaName: "Ibeju-Lekki",
    chairman: "Hon. Sola Adeleke",
    address: "Ibeju LCDA Secretariat, Akodo, Lagos",
    phone: "+234-1-4930910",
    zone: "Suburban",
    established: "2002",
    headquarters: "Akodo",
    coordinates: { lat: 6.4353, lng: 3.8087 },
    bio: "Ibeju LCDA covers the western part of Ibeju-Lekki including the Dangote Refinery site and the Lekki Deep Sea Port. It is the epicentre of Nigeria's industrial transformation.",
    knownFor: ["Dangote Refinery", "Lekki Deep Sea Port", "Industrial zone", "Investment hub"],
    wards: [
      { id: "ibeju-w1", name: "Ward 1 — Akodo", description: "Akodo town — LGA headquarters area." },
      { id: "ibeju-w2", name: "Ward 2 — Dangote Refinery Area", description: "Refinery community and support services." },
      { id: "ibeju-w3", name: "Ward 3 — Lekki Port", description: "Lekki Deep Sea Port vicinity." },
      { id: "ibeju-w4", name: "Ward 4 — Eleranigbe", description: "Eleranigbe farming and fishing community." },
      { id: "ibeju-w5", name: "Ward 5 — Ise-Town", description: "Ise traditional community area." },
    ],
  },
  {
    id: "lekki-lcda",
    name: "Lekki LCDA",
    parentLgaId: "ibeju-lekki",
    parentLgaName: "Ibeju-Lekki",
    chairman: "Hon. Rotimi Ajakaye",
    address: "Lekki LCDA Secretariat, Lekki Free Zone, Lagos",
    phone: "+234-1-4930920",
    zone: "Suburban",
    established: "2002",
    headquarters: "Lekki Free Zone",
    coordinates: { lat: 6.4500, lng: 3.9500 },
    bio: "Lekki LCDA covers the Lekki Free Trade Zone and surrounding beach communities. It is home to the La Campagne Tropicana resort and Eleko Beach, making it both an industrial and tourism destination.",
    knownFor: ["Lekki Free Zone", "La Campagne Tropicana", "Eleko Beach", "Tourism & industry"],
    wards: [
      { id: "lekki-w1", name: "Ward 1 — Lekki Free Zone", description: "Lekki Free Trade Zone and industrial area." },
      { id: "lekki-w2", name: "Ward 2 — Eleko Beach", description: "Eleko Beach community." },
      { id: "lekki-w3", name: "Ward 3 — Folu-Ise", description: "Folu-Ise farming community." },
      { id: "lekki-w4", name: "Ward 4 — La Campagne Area", description: "La Campagne Tropicana resort environs." },
      { id: "lekki-w5", name: "Ward 5 — Orimedu", description: "Orimedu coastal fishing community." },
    ],
  },

  // ── IFAKO-IJAIYE LGA ──────────────────────────────────────────────────────

  {
    id: "ifako-ijaye-lcda",
    name: "Ifako-Ijaye LCDA",
    parentLgaId: "ifako-ijaiye",
    parentLgaName: "Ifako-Ijaiye",
    chairman: "Hon. Ayo Bankole",
    address: "Ifako-Ijaye LCDA Secretariat, Ogba, Lagos",
    phone: "+234-1-4931010",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ogba",
    coordinates: { lat: 6.6463, lng: 3.3404 },
    bio: "Ifako-Ijaye LCDA covers the Ogba commercial district and Ifako residential areas. Ogba is one of Lagos's most thriving middle-class neighbourhoods with shopping malls, schools and businesses.",
    knownFor: ["Ogba Shopping District", "Middle-class residences", "Commercial hub"],
    wards: [
      { id: "ifako-ijaye-w1", name: "Ward 1 — Ogba Central", description: "Ogba town centre and market." },
      { id: "ifako-ijaye-w2", name: "Ward 2 — Ifako", description: "Ifako residential community." },
      { id: "ifako-ijaye-w3", name: "Ward 3 — Ijaiye", description: "Ijaiye community area." },
      { id: "ifako-ijaye-w4", name: "Ward 4 — Agbado-Oke", description: "Agbado elevated community." },
      { id: "ifako-ijaye-w5", name: "Ward 5 — Iju-Ishaga", description: "Iju-Ishaga residential area." },
    ],
  },
  {
    id: "ojokoro-lcda",
    name: "Ojokoro LCDA",
    parentLgaId: "ifako-ijaiye",
    parentLgaName: "Ifako-Ijaiye",
    chairman: "Hon. Biodun Ogunwale",
    address: "Ojokoro LCDA Secretariat, Agbado, Lagos",
    phone: "+234-1-4931020",
    zone: "Mainland",
    established: "2002",
    headquarters: "Agbado",
    coordinates: { lat: 6.6600, lng: 3.2900 },
    bio: "Ojokoro LCDA covers the Agbado-Ojokoro corridor near the Ogun State border. The area has significant railway heritage and is a growing commuter community.",
    knownFor: ["Agbado railway junction", "Border community", "Commuter suburb"],
    wards: [
      { id: "ojokoro-w1", name: "Ward 1 — Agbado", description: "Agbado railway junction community." },
      { id: "ojokoro-w2", name: "Ward 2 — Ojokoro", description: "Ojokoro central community." },
      { id: "ojokoro-w3", name: "Ward 3 — Akute-Odo", description: "Akute-Odo border community." },
      { id: "ojokoro-w4", name: "Ward 4 — Ijaiye-Ojokoro", description: "Ijaiye-Ojokoro residential stretch." },
      { id: "ojokoro-w5", name: "Ward 5 — Ile-Zik", description: "Ile-Zik community area." },
    ],
  },

  // ── IKEJA LGA ─────────────────────────────────────────────────────────────

  {
    id: "ojodu-lcda",
    name: "Ojodu LCDA",
    parentLgaId: "ikeja",
    parentLgaName: "Ikeja",
    chairman: "Hon. Segun Odunmbaku",
    address: "Ojodu LCDA Secretariat, Ojodu, Lagos",
    phone: "+234-1-4931110",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ojodu",
    coordinates: { lat: 6.6350, lng: 3.3550 },
    bio: "Ojodu LCDA covers the Ojodu-Berger area, one of Lagos's busiest transport interchanges connecting the Mainland to Ogun State. The area hosts the Lagos State Public Works Corporation headquarters.",
    knownFor: ["Berger Bus Stop", "Transport interchange", "LSPWC headquarters", "Residential estates"],
    wards: [
      { id: "ojodu-w1", name: "Ward 1 — Berger", description: "Berger bus stop and interchange area." },
      { id: "ojodu-w2", name: "Ward 2 — Ojodu Central", description: "Ojodu town centre." },
      { id: "ojodu-w3", name: "Ward 3 — Omole Phase 1", description: "Omole Phase 1 estate." },
      { id: "ojodu-w4", name: "Ward 4 — Omole Phase 2", description: "Omole Phase 2 residential estate." },
      { id: "ojodu-w5", name: "Ward 5 — Isheri-North", description: "Isheri-North community." },
    ],
  },
  {
    id: "onigbongbo-lcda",
    name: "Onigbongbo LCDA",
    parentLgaId: "ikeja",
    parentLgaName: "Ikeja",
    chairman: "Hon. Tunde Aromolewa",
    address: "Onigbongbo LCDA Secretariat, Maryland, Lagos",
    phone: "+234-1-4931120",
    zone: "Mainland",
    established: "2002",
    headquarters: "Maryland",
    coordinates: { lat: 6.5700, lng: 3.3600 },
    bio: "Onigbongbo LCDA covers the Maryland-Ikeja axis, home to the Murtala Muhammed Airport, Computer Village and the Ikeja GRA. This is the administrative and commercial heart of Lagos State.",
    knownFor: ["Murtala Muhammed Airport", "Computer Village", "Ikeja GRA", "Maryland Mall"],
    wards: [
      { id: "onigbongbo-w1", name: "Ward 1 — Maryland", description: "Maryland commercial district." },
      { id: "onigbongbo-w2", name: "Ward 2 — Ikeja GRA", description: "Ikeja Government Reserved Area." },
      { id: "onigbongbo-w3", name: "Ward 3 — Computer Village", description: "Computer Village tech market area." },
      { id: "onigbongbo-w4", name: "Ward 4 — Alausa", description: "Alausa Secretariat government district." },
      { id: "onigbongbo-w5", name: "Ward 5 — Airport Road", description: "Airport Road corridor and surrounds." },
    ],
  },

  // ── IKORODU LGA ───────────────────────────────────────────────────────────

  {
    id: "ikorodu-north-lcda",
    name: "Ikorodu North LCDA",
    parentLgaId: "ikorodu",
    parentLgaName: "Ikorodu",
    chairman: "Hon. Lekan Fatodu",
    address: "Ikorodu North LCDA Secretariat, Ikorodu, Lagos",
    phone: "+234-1-4931210",
    zone: "Suburban",
    established: "2002",
    headquarters: "Ikorodu North",
    coordinates: { lat: 6.6500, lng: 3.5200 },
    bio: "Ikorodu North LCDA covers the northern part of the Ikorodu urban area. It has significant agricultural land and is a gateway to the Lagos-Ibadan Expressway via Sagamu-Ore Road.",
    knownFor: ["Agricultural communities", "Sagamu Road corridor", "Residential growth"],
    wards: [
      { id: "ikorodu-north-w1", name: "Ward 1 — Ikorodu Town", description: "Ikorodu central town area." },
      { id: "ikorodu-north-w2", name: "Ward 2 — Odogunyan", description: "Odogunyan community." },
      { id: "ikorodu-north-w3", name: "Ward 3 — Itamaga", description: "Itamaga residential area." },
      { id: "ikorodu-north-w4", name: "Ward 4 — Agbowa-Ikosi", description: "Agbowa-Ikosi community." },
      { id: "ikorodu-north-w5", name: "Ward 5 — Ijede", description: "Ijede fishing and farming community." },
    ],
  },
  {
    id: "ikorodu-west-lcda",
    name: "Ikorodu West LCDA",
    parentLgaId: "ikorodu",
    parentLgaName: "Ikorodu",
    chairman: "Hon. Yetunde Adewale",
    address: "Ikorodu West LCDA Secretariat, Ikorodu, Lagos",
    phone: "+234-1-4931220",
    zone: "Suburban",
    established: "2002",
    headquarters: "Ikorodu West",
    coordinates: { lat: 6.6100, lng: 3.4900 },
    bio: "Ikorodu West LCDA covers the western section of the Ikorodu municipality, closest to the Lagos Lagoon ferry terminal.",
    knownFor: ["Ferry terminal", "Lagoon communities", "Transport hub"],
    wards: [
      { id: "ikorodu-west-w1", name: "Ward 1 — Ferry Terminal", description: "Ferry terminal and waterfront area." },
      { id: "ikorodu-west-w2", name: "Ward 2 — Gberigbe", description: "Gberigbe community." },
      { id: "ikorodu-west-w3", name: "Ward 3 — Adamo", description: "Adamo residential area." },
      { id: "ikorodu-west-w4", name: "Ward 4 — Lasunwon", description: "Lasunwon community." },
      { id: "ikorodu-west-w5", name: "Ward 5 — Owode-Ibeshe", description: "Owode-Ibeshe waterfront." },
    ],
  },
  {
    id: "igbogbo-bayeku-lcda",
    name: "Igbogbo-Bayeku LCDA",
    parentLgaId: "ikorodu",
    parentLgaName: "Ikorodu",
    chairman: "Hon. Rotimi Adesanya",
    address: "Igbogbo-Bayeku LCDA Secretariat, Igbogbo, Lagos",
    phone: "+234-1-4931230",
    zone: "Suburban",
    established: "2002",
    headquarters: "Igbogbo",
    coordinates: { lat: 6.5900, lng: 3.5400 },
    bio: "Igbogbo-Bayeku LCDA covers the Igbogbo and Bayeku lagoon communities, known for fishing and small-scale aquaculture.",
    knownFor: ["Fishing communities", "Aquaculture", "Lagoon lifestyle"],
    wards: [
      { id: "igbogbo-bayeku-w1", name: "Ward 1 — Igbogbo", description: "Igbogbo town area." },
      { id: "igbogbo-bayeku-w2", name: "Ward 2 — Bayeku", description: "Bayeku lagoon community." },
      { id: "igbogbo-bayeku-w3", name: "Ward 3 — Ibeshe", description: "Ibeshe riverside community." },
      { id: "igbogbo-bayeku-w4", name: "Ward 4 — Ota-Ikosi", description: "Ota-Ikosi area." },
    ],
  },
  {
    id: "imota-lcda",
    name: "Imota LCDA",
    parentLgaId: "ikorodu",
    parentLgaName: "Ikorodu",
    chairman: "Hon. Mulikat Efuwape",
    address: "Imota LCDA Secretariat, Imota, Lagos",
    phone: "+234-1-4931240",
    zone: "Suburban",
    established: "2002",
    headquarters: "Imota",
    coordinates: { lat: 6.6400, lng: 3.6000 },
    bio: "Imota LCDA is home to the Dangote Rice Mill — one of the largest rice processing plants in Africa — which has transformed the local economy significantly.",
    knownFor: ["Dangote Rice Mill", "Agricultural processing", "Rural farming"],
    wards: [
      { id: "imota-w1", name: "Ward 1 — Imota Town", description: "Imota town centre." },
      { id: "imota-w2", name: "Ward 2 — Rice Mill Area", description: "Dangote Rice Mill community." },
      { id: "imota-w3", name: "Ward 3 — Agbowa", description: "Agbowa farming community." },
      { id: "imota-w4", name: "Ward 4 — Araromi", description: "Araromi village area." },
    ],
  },
  {
    id: "ikosi-isheri-lcda",
    name: "Ikosi-Isheri LCDA",
    parentLgaId: "ikorodu",
    parentLgaName: "Ikorodu",
    chairman: "Hon. Femi Owolade",
    address: "Ikosi-Isheri LCDA Secretariat, Ikosi, Lagos",
    phone: "+234-1-4931250",
    zone: "Suburban",
    established: "2002",
    headquarters: "Ikosi",
    coordinates: { lat: 6.6200, lng: 3.4600 },
    bio: "Ikosi-Isheri LCDA covers the Ikosi and Isheri communities at the southern tip of Ikorodu, bordering Kosofe LGA. The area has growing residential estates.",
    knownFor: ["Residential growth", "Isheri waterway", "Southern Ikorodu"],
    wards: [
      { id: "ikosi-isheri-w1", name: "Ward 1 — Ikosi", description: "Ikosi main community." },
      { id: "ikosi-isheri-w2", name: "Ward 2 — Isheri-Osun", description: "Isheri-Osun waterway community." },
      { id: "ikosi-isheri-w3", name: "Ward 3 — Owutu", description: "Owutu residential area." },
      { id: "ikosi-isheri-w4", name: "Ward 4 — Ketu-Ikorodu", description: "Ketu-Ikorodu border area." },
    ],
  },

  // ── KOSOFE LGA ────────────────────────────────────────────────────────────

  {
    id: "kosofe-lcda",
    name: "Kosofe LCDA",
    parentLgaId: "kosofe",
    parentLgaName: "Kosofe",
    chairman: "Hon. Segun Adewale",
    address: "Kosofe LCDA Secretariat, Ogudu, Lagos",
    phone: "+234-1-4931310",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ogudu",
    coordinates: { lat: 6.5833, lng: 3.4167 },
    bio: "Kosofe LCDA covers Ogudu, Ojota and surrounding communities. The Ojota transport interchange is one of the busiest in Lagos, serving routes across the Mainland and beyond.",
    knownFor: ["Ojota bus terminal", "Ogudu GRA", "Transport hub", "NASFAT HQ"],
    wards: [
      { id: "kosofe-w1", name: "Ward 1 — Ojota", description: "Ojota bus terminal and surrounds." },
      { id: "kosofe-w2", name: "Ward 2 — Ogudu", description: "Ogudu residential and GRA area." },
      { id: "kosofe-w3", name: "Ward 3 — Alapere", description: "Alapere estate community." },
      { id: "kosofe-w4", name: "Ward 4 — Owode-Onirin", description: "Owode-Onirin market area." },
      { id: "kosofe-w5", name: "Ward 5 — Oregun", description: "Oregun industrial and residential area." },
    ],
  },
  {
    id: "agboyi-ketu-lcda",
    name: "Agboyi-Ketu LCDA",
    parentLgaId: "kosofe",
    parentLgaName: "Kosofe",
    chairman: "Hon. Tunji Olawale",
    address: "Agboyi-Ketu LCDA Secretariat, Ketu, Lagos",
    phone: "+234-1-4931320",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ketu",
    coordinates: { lat: 6.5970, lng: 3.3870 },
    bio: "Agboyi-Ketu LCDA covers the Ketu and Mile 12 communities. Mile 12 International Market is one of the largest fresh produce markets in West Africa, serving as the primary food distribution hub for Lagos.",
    knownFor: ["Mile 12 produce market", "Ketu bus terminal", "Food distribution hub"],
    wards: [
      { id: "agboyi-ketu-w1", name: "Ward 1 — Ketu", description: "Ketu bus terminal and residential area." },
      { id: "agboyi-ketu-w2", name: "Ward 2 — Mile 12", description: "Mile 12 International Market area." },
      { id: "agboyi-ketu-w3", name: "Ward 3 — Agboyi", description: "Agboyi waterfront community." },
      { id: "agboyi-ketu-w4", name: "Ward 4 — Agiliti", description: "Agiliti community area." },
      { id: "agboyi-ketu-w5", name: "Ward 5 — Owode-Elede", description: "Owode-Elede border community." },
    ],
  },

  // ── LAGOS MAINLAND LGA ────────────────────────────────────────────────────

  {
    id: "yaba-lcda",
    name: "Yaba LCDA",
    parentLgaId: "lagos-mainland",
    parentLgaName: "Lagos Mainland",
    chairman: "Hon. Babatunde Gbadamosi",
    address: "Yaba LCDA Secretariat, Yaba, Lagos",
    phone: "+234-1-4931510",
    zone: "Mainland",
    established: "2002",
    headquarters: "Yaba",
    coordinates: { lat: 6.5095, lng: 3.3711 },
    bio: "Yaba LCDA covers Yaba, Ebute Metta, Makoko and Sabo. Yaba is Nigeria's premier technology ecosystem and educational hub hosting CcHub, dozens of startups and several universities. Makoko is Africa's most photographed floating community.",
    knownFor: ["Yaba tech hub", "CcHub Nigeria", "UNILAG proximity", "Makoko floating village", "YABATECH"],
    wards: [
      { id: "yaba-w1", name: "Ward 1 — Yaba Central", description: "Yaba market and tech district." },
      { id: "yaba-w2", name: "Ward 2 — Ebute Metta East", description: "Eastern Ebute Metta." },
      { id: "yaba-w3", name: "Ward 3 — Ebute Metta West", description: "Western Ebute Metta railway area." },
      { id: "yaba-w4", name: "Ward 4 — Makoko", description: "Makoko floating community on the lagoon." },
      { id: "yaba-w5", name: "Ward 5 — Sabo", description: "Sabo community area." },
      { id: "yaba-w6", name: "Ward 6 — Oyingbo", description: "Oyingbo market area." },
    ],
  },

  // ── MUSHIN LGA ────────────────────────────────────────────────────────────

  {
    id: "mushin-lcda",
    name: "Mushin LCDA",
    parentLgaId: "mushin",
    parentLgaName: "Mushin",
    chairman: "Hon. Ayo Olatunji",
    address: "Mushin LCDA Secretariat, Mushin, Lagos",
    phone: "+234-1-4931610",
    zone: "Mainland",
    established: "2002",
    headquarters: "Mushin",
    coordinates: { lat: 6.5277, lng: 3.3561 },
    bio: "Mushin LCDA covers the core Mushin township, one of Lagos's most commercially vibrant working-class communities. The area is famous for Ladipo auto-parts market and its rich musical heritage.",
    knownFor: ["Ladipo Auto Market", "Music culture", "Commercial markets", "Urban resilience"],
    wards: [
      { id: "mushin-w1", name: "Ward 1 — Mushin Central", description: "Mushin town centre and main market." },
      { id: "mushin-w2", name: "Ward 2 — Ladipo", description: "Ladipo auto-parts market area." },
      { id: "mushin-w3", name: "Ward 3 — Idi-Oro", description: "Idi-Oro community and bus terminal." },
      { id: "mushin-w4", name: "Ward 4 — Ojuwoye", description: "Ojuwoye market area." },
      { id: "mushin-w5", name: "Ward 5 — Papa Ajao", description: "Papa Ajao market community." },
    ],
  },
  {
    id: "odi-olowo-ojuwoye-lcda",
    name: "Odi-Olowo/Ojuwoye LCDA",
    parentLgaId: "mushin",
    parentLgaName: "Mushin",
    chairman: "Hon. Taofeeq Animasaun",
    address: "Odi-Olowo LCDA Secretariat, Idi-Araba, Lagos",
    phone: "+234-1-4931620",
    zone: "Mainland",
    established: "2002",
    headquarters: "Idi-Araba",
    coordinates: { lat: 6.5150, lng: 3.3500 },
    bio: "Odi-Olowo/Ojuwoye LCDA covers the area around Idi-Araba and the LUTH hospital district. It borders Surulere and has a mix of residential and medical service communities.",
    knownFor: ["LUTH proximity", "Medical corridor", "Residential community"],
    wards: [
      { id: "odi-olowo-w1", name: "Ward 1 — Idi-Araba", description: "Idi-Araba LUTH hospital district." },
      { id: "odi-olowo-w2", name: "Ward 2 — Odi-Olowo", description: "Odi-Olowo residential area." },
      { id: "odi-olowo-w3", name: "Ward 3 — Ojuwoye", description: "Ojuwoye community and market." },
      { id: "odi-olowo-w4", name: "Ward 4 — Agege Motor Road", description: "Agege Motor Road corridor." },
      { id: "odi-olowo-w5", name: "Ward 5 — Idi-Mangoro", description: "Idi-Mangoro community." },
    ],
  },

  // ── OJO LGA ───────────────────────────────────────────────────────────────

  {
    id: "ojo-lcda",
    name: "Ojo LCDA",
    parentLgaId: "ojo",
    parentLgaName: "Ojo",
    chairman: "Hon. Damola Adesanya",
    address: "Ojo LCDA Secretariat, Ojo, Lagos",
    phone: "+234-1-4931710",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ojo",
    coordinates: { lat: 6.4698, lng: 3.2067 },
    bio: "Ojo LCDA covers the Ojo township and military cantonment areas. The area hosts Lagos State University's main campus and the Ojo Military Cantonment — one of the largest in Nigeria.",
    knownFor: ["LASU Campus", "Ojo Military Cantonment", "Badagry Expressway", "Atlantic coastline"],
    wards: [
      { id: "ojo-w1", name: "Ward 1 — Ojo Town", description: "Ojo central town and market." },
      { id: "ojo-w2", name: "Ward 2 — Cantonment", description: "Military cantonment area." },
      { id: "ojo-w3", name: "Ward 3 — LASU Area", description: "Lagos State University campus environs." },
      { id: "ojo-w4", name: "Ward 4 — Alaba", description: "Alaba International Market area." },
      { id: "ojo-w5", name: "Ward 5 — Trade Fair Junction", description: "International Trade Fair Complex junction." },
    ],
  },
  {
    id: "oto-awori-lcda",
    name: "Oto-Awori LCDA",
    parentLgaId: "ojo",
    parentLgaName: "Ojo",
    chairman: "Hon. Tunde Fatula",
    address: "Oto-Awori LCDA Secretariat, Oto-Awori, Lagos",
    phone: "+234-1-4931720",
    zone: "Mainland",
    established: "2002",
    headquarters: "Oto-Awori",
    coordinates: { lat: 6.4000, lng: 3.1500 },
    bio: "Oto-Awori LCDA covers the indigenous Awori communities in the western part of Ojo LGA along the Lagos-Badagry Expressway. These are among the oldest native settlements in the Lagos area.",
    knownFor: ["Awori indigenous communities", "Coastal fishing", "Ancient settlements", "Expressway corridor"],
    wards: [
      { id: "oto-awori-w1", name: "Ward 1 — Oto", description: "Oto indigenous community." },
      { id: "oto-awori-w2", name: "Ward 2 — Awori", description: "Awori central settlement." },
      { id: "oto-awori-w3", name: "Ward 3 — Ibereko", description: "Ibereko coastal community." },
      { id: "oto-awori-w4", name: "Ward 4 — Ilogbo", description: "Ilogbo village area." },
      { id: "oto-awori-w5", name: "Ward 5 — Imore", description: "Imore coastal community." },
    ],
  },

  // ── OSHODI-ISOLO LGA ──────────────────────────────────────────────────────

  {
    id: "ejigbo-lcda",
    name: "Ejigbo LCDA",
    parentLgaId: "oshodi-isolo",
    parentLgaName: "Oshodi-Isolo",
    chairman: "Hon. Muyiwa Agunbiade",
    address: "Ejigbo LCDA Secretariat, Ejigbo, Lagos",
    phone: "+234-1-4931810",
    zone: "Mainland",
    established: "2002",
    headquarters: "Ejigbo",
    coordinates: { lat: 6.5100, lng: 3.3200 },
    bio: "Ejigbo LCDA covers the Ejigbo and Ishaga communities in the southern part of Oshodi-Isolo LGA. The area has significant residential estates and light industrial activity.",
    knownFor: ["Residential estates", "Light industry", "Expressway corridor"],
    wards: [
      { id: "ejigbo-w1", name: "Ward 1 — Ejigbo Central", description: "Ejigbo town centre." },
      { id: "ejigbo-w2", name: "Ward 2 — Ishaga", description: "Ishaga residential community." },
      { id: "ejigbo-w3", name: "Ward 3 — Powerline", description: "Powerline road community." },
      { id: "ejigbo-w4", name: "Ward 4 — Jakande Estate", description: "Jakande housing estate." },
      { id: "ejigbo-w5", name: "Ward 5 — Airport Road", description: "Airport Road residential area." },
    ],
  },

  // ── SHOMOLU LGA ───────────────────────────────────────────────────────────

  {
    id: "bariga-lcda",
    name: "Bariga LCDA",
    parentLgaId: "shomolu",
    parentLgaName: "Shomolu",
    chairman: "Hon. Lanre Adeyemi",
    address: "Bariga LCDA Secretariat, Bariga, Lagos",
    phone: "+234-1-4931910",
    zone: "Mainland",
    established: "2002",
    headquarters: "Bariga",
    coordinates: { lat: 6.5300, lng: 3.3900 },
    bio: "Bariga LCDA covers the Bariga waterfront community on the edge of the Lagos Lagoon. The area has a vibrant creative scene and strong community associations.",
    knownFor: ["Waterfront community", "Creative culture", "Lagoon access", "Bariga market"],
    wards: [
      { id: "bariga-w1", name: "Ward 1 — Bariga Central", description: "Bariga town centre." },
      { id: "bariga-w2", name: "Ward 2 — Abaranje-Bariga", description: "Abaranje area of Bariga." },
      { id: "bariga-w3", name: "Ward 3 — Waterfront", description: "Bariga lagoon waterfront community." },
      { id: "bariga-w4", name: "Ward 4 — Oke-Ira", description: "Oke-Ira Bariga community." },
      { id: "bariga-w5", name: "Ward 5 — Oworonshoki", description: "Oworonshoki area near expressway." },
    ],
  },
  {
    id: "shomolu-lcda",
    name: "Shomolu LCDA",
    parentLgaId: "shomolu",
    parentLgaName: "Shomolu",
    chairman: "Hon. Olumide Abiodun",
    address: "Shomolu LCDA Secretariat, Shomolu, Lagos",
    phone: "+234-1-4931920",
    zone: "Mainland",
    established: "2002",
    headquarters: "Shomolu",
    coordinates: { lat: 6.5356, lng: 3.3861 },
    bio: "Shomolu LCDA covers the Shomolu and Gbagada communities. Gbagada is one of Lagos's most desirable middle-class residential areas with well-maintained roads and strong estate culture.",
    knownFor: ["Gbagada Estate", "Residential quality", "Third Mainland Bridge access", "Anthony Village"],
    wards: [
      { id: "shomolu-w1", name: "Ward 1 — Shomolu Central", description: "Shomolu main community area." },
      { id: "shomolu-w2", name: "Ward 2 — Gbagada Phase 1", description: "Gbagada Phase 1 residential estate." },
      { id: "shomolu-w3", name: "Ward 3 — Gbagada Phase 2", description: "Gbagada Phase 2 residential estate." },
      { id: "shomolu-w4", name: "Ward 4 — Anthony Village", description: "Anthony Village residential area." },
      { id: "shomolu-w5", name: "Ward 5 — Pedro", description: "Pedro community area." },
    ],
  },

  // ── SURULERE LGA ──────────────────────────────────────────────────────────

  {
    id: "itire-ikate-lcda",
    name: "Itire-Ikate LCDA",
    parentLgaId: "surulere",
    parentLgaName: "Surulere",
    chairman: "Hon. Babatunde Adeyemo",
    address: "Itire-Ikate LCDA Secretariat, Itire, Lagos",
    phone: "+234-1-4932010",
    zone: "Mainland",
    established: "2002",
    headquarters: "Itire",
    coordinates: { lat: 6.4800, lng: 3.3500 },
    bio: "Itire-Ikate LCDA covers the Itire and Ikate communities on the boundary of Surulere and Eti-Osa. The area bridges the creative Surulere culture with the commercial Lekki axis.",
    knownFor: ["Boundary community", "Itire market", "Mixed-use development"],
    wards: [
      { id: "itire-ikate-w1", name: "Ward 1 — Itire", description: "Itire central community." },
      { id: "itire-ikate-w2", name: "Ward 2 — Ikate", description: "Ikate residential community." },
      { id: "itire-ikate-w3", name: "Ward 3 — Lawanson", description: "Lawanson area community." },
      { id: "itire-ikate-w4", name: "Ward 4 — Iponri", description: "Iponri residential area." },
      { id: "itire-ikate-w5", name: "Ward 5 — Costain", description: "Costain waterfront community." },
    ],
  },
  {
    id: "surulere-lcda",
    name: "Surulere LCDA",
    parentLgaId: "surulere",
    parentLgaName: "Surulere",
    chairman: "Hon. Gbadebo Akosile",
    address: "Surulere LCDA Secretariat, Surulere, Lagos",
    phone: "+234-1-4932020",
    zone: "Mainland",
    established: "2002",
    headquarters: "Surulere",
    coordinates: { lat: 6.4969, lng: 3.3481 },
    bio: "Surulere LCDA covers the core Surulere township — home to the National Stadium, Teslim Balogun Stadium, National Theatre and LUTH. This is Lagos's cultural and sporting heartland.",
    knownFor: ["National Stadium", "National Theatre", "LUTH", "Fela Kuti heritage", "Adeniran Ogunsanya Street"],
    wards: [
      { id: "surulere-w1", name: "Ward 1 — Adeniran Ogunsanya", description: "Adeniran Ogunsanya Street commercial district." },
      { id: "surulere-w2", name: "Ward 2 — National Stadium", description: "National Stadium and surrounds." },
      { id: "surulere-w3", name: "Ward 3 — Shitta", description: "Shitta-Bey Mosque area." },
      { id: "surulere-w4", name: "Ward 4 — Eric Moore", description: "Eric Moore residential area." },
      { id: "surulere-w5", name: "Ward 5 — Aguda", description: "Aguda residential community." },
      { id: "surulere-w6", name: "Ward 6 — Iponri Estate", description: "Iponri Estate residential area." },
    ],
  },
];

export const getLCDAById = (id: string) => lcdas.find(l => l.id === id);
export const getLCDAsByParentLGA = (lgaId: string) => lcdas.filter(l => l.parentLgaId === lgaId);
export const getWardById = (wardId: string) => {
  for (const lcda of lcdas) {
    const ward = lcda.wards.find(w => w.id === wardId);
    if (ward) return { ward, lcda };
  }
  return null;
};
