export type LGAOfficer = {
  name: string;
  title: string;
};

export type LGA = {
  id: string;
  name: string;
  chairman: string;
  viceChairman?: string;
  officers: LGAOfficer[];
  address: string;
  phone: string;
  email?: string;
  zone: "Island" | "Mainland" | "Suburban";
  wards: number;
  population: string;
  headquarters: string;
  area: string;
  coordinates: { lat: number; lng: number };
  established: string;
  bio: string;
  history: string;
  landmarks: string[];
  knownFor: string[];
  localCouncilDevelopmentAreas: string[];
  postalCode?: string;
};

export const lgas: LGA[] = [
  {
    id: "agege",
    name: "Agege",
    chairman: "Hon. Ganiyu Egunjobi",
    viceChairman: "Hon. Seun Adeyemi",
    officers: [
      { name: "Mr. Babatunde Adewale", title: "Head of Local Government Administration" },
      { name: "Mrs. Funke Olatunji", title: "Director of Finance" },
    ],
    address: "Agege Local Government Secretariat, Old Abeokuta Road, Agege, Lagos",
    phone: "+234-1-4930100",
    email: "info@agege.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "459,939",
    headquarters: "Agege",
    area: "22 km²",
    coordinates: { lat: 6.6193, lng: 3.3192 },
    established: "1976",
    postalCode: "100283",
    bio: "Agege is a densely populated local government area located in the northwestern part of Lagos Mainland. Known for its vibrant commercial activities and diverse population, Agege is one of the most industrious communities in Lagos State. The area is a major hub for the textile and garment trade, with Agege market being one of the busiest in the state.",
    history: "Agege was originally settled by Yoruba farmers and has grown significantly since the colonial era. It was officially recognised as a Local Government Area in 1976 during the local government reforms under General Murtala Muhammed. The area was historically known for cocoa farming before urbanisation transformed it into a commercial and residential district. Its proximity to the Lagos-Abeokuta Expressway made it a strategic gateway between Lagos and Ogun State.",
    landmarks: ["Agege Market", "Agege Stadium", "Our Lady of Apostles Secondary School", "Lagos-Abeokuta Expressway", "Pen Cinema Roundabout"],
    knownFor: ["Textile & garment trade", "Agege bread", "Dense urban markets", "Football (Shooting Stars)"],
    localCouncilDevelopmentAreas: ["Agege LCDA", "Orile-Agege LCDA"],
  },
  {
    id: "ajeromi-ifelodun",
    name: "Ajeromi-Ifelodun",
    chairman: "Hon. Fatai Ayoola",
    officers: [
      { name: "Mr. Lekan Salami", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Hospital Road, Ajegunle, Lagos",
    phone: "+234-1-4930200",
    email: "info@ajeromi.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 10,
    population: "688,400",
    headquarters: "Ajegunle",
    area: "18 km²",
    coordinates: { lat: 6.4698, lng: 3.3541 },
    established: "1976",
    postalCode: "102213",
    bio: "Ajeromi-Ifelodun is one of the most densely populated local government areas in Nigeria, home to the famous Ajegunle community. Despite its challenges, the area has produced some of Nigeria's finest musicians, athletes and professionals. It is a vibrant melting pot of cultures with a strong sense of community identity.",
    history: "Ajegunle's origins trace back to the mid-20th century when workers drawn to the Lagos port and industrial zones settled in the area. The Ifelodun section has older roots tied to indigenous Yoruba settlements along the Lagos lagoon. In 1976 the two areas were merged into one LGA. Ajegunle became associated with working-class resilience and gave rise to legendary musicians including Daddy Showkey and Baba Fryo.",
    landmarks: ["Ajegunle Market", "Wharf Road", "Boundary Bus Stop", "International Trade Fair Proximity"],
    knownFor: ["Afrobeats & music culture", "Boxing and football", "Dense urban community", "Cultural diversity"],
    localCouncilDevelopmentAreas: ["Ajeromi LCDA", "Ifelodun LCDA"],
  },
  {
    id: "alimosho",
    name: "Alimosho",
    chairman: "Hon. Jelili Sulaimon",
    officers: [
      { name: "Mr. Tunji Adebayo", title: "Head of Local Government Administration" },
      { name: "Mrs. Adunola Okonkwo", title: "Director, Works & Infrastructure" },
    ],
    address: "LG Secretariat, Alimosho, Lagos",
    phone: "+234-1-4930300",
    email: "info@alimosho.lagosstate.gov.ng",
    zone: "Suburban",
    wards: 12,
    population: "1,288,714",
    headquarters: "Alimosho",
    area: "233 km²",
    coordinates: { lat: 6.6058, lng: 3.2478 },
    established: "1991",
    postalCode: "100265",
    bio: "Alimosho is the largest and most populous Local Government Area in Lagos State and in Nigeria. Spanning over 233 square kilometres, it encompasses diverse communities including Egbe, Idimu, Ipaja, Igando and Satellite Town. The area is a major residential hub with a booming real estate market and growing commercial activity.",
    history: "Alimosho was carved out as a separate LGA in 1991 from the old Agege LGA as part of the military government's local government restructuring. Before urbanisation, the area was largely agrarian with small Yoruba farming settlements. The construction of the Lagos-Abeokuta Expressway and later the development of estates such as Jakande Estate and Satellite Town spurred massive population growth. Today it hosts over 1.2 million residents making it the most populous LGA in Nigeria.",
    landmarks: ["Egbe-Idimu Market", "Jakande Estate", "Satellite Town", "Ipaja Road", "Akowonjo Roundabout", "Command Secondary School"],
    knownFor: ["Largest LGA in Nigeria", "Massive residential estates", "Real estate growth", "Igando market"],
    localCouncilDevelopmentAreas: ["Egbe-Idimu LCDA", "Igando-Ikotun LCDA", "Ikotun-Igando LCDA", "Isolo LCDA", "Mosan-Okunola LCDA"],
  },
  {
    id: "amuwo-odofin",
    name: "Amuwo-Odofin",
    chairman: "Hon. Engr. Sola Abiodun",
    officers: [
      { name: "Mr. Biodun Afolabi", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Mile 2, Lagos",
    phone: "+234-1-4930400",
    email: "info@amuwo.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 10,
    population: "317,720",
    headquarters: "Mile 2",
    area: "140 km²",
    coordinates: { lat: 6.4728, lng: 3.2944 },
    established: "1991",
    postalCode: "102102",
    bio: "Amuwo-Odofin is a strategically located LGA covering Mile 2, Festac Town, Satellite Town and the Atlas Cove petroleum facility. It is home to the iconic FESTAC Town — the site of the 1977 Second World Black and African Festival of Arts and Culture — which remains one of Africa's most ambitious housing projects.",
    history: "Amuwo-Odofin was created in 1991. Its most significant historical event was hosting FESTAC '77, a pan-African cultural festival that brought together over 17,000 artists, writers and performers from 59 African nations and the diaspora. The Festac housing estate built for the festival became one of Lagos's most organised residential communities. The LGA also hosts the Atlas Cove petroleum depot, a critical fuel storage and distribution hub for Nigeria.",
    landmarks: ["FESTAC Town", "Mile 2 Bus Terminal", "Atlas Cove Petroleum Depot", "FESTAC 77 Monument", "International Trade Fair Complex"],
    knownFor: ["FESTAC '77 heritage", "Organised residential estates", "Mile 2 transport hub", "Atlas Cove fuel depot"],
    localCouncilDevelopmentAreas: ["Amuwo-Odofin LCDA", "Oriade LCDA"],
  },
  {
    id: "apapa",
    name: "Apapa",
    chairman: "Hon. Idowu Ganiyu",
    officers: [
      { name: "Mr. Emeka Obi", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Burma Road, Apapa, Lagos",
    phone: "+234-1-4930500",
    email: "info@apapa.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 8,
    population: "217,362",
    headquarters: "Apapa",
    area: "20 km²",
    coordinates: { lat: 6.4481, lng: 3.3591 },
    established: "1976",
    postalCode: "101245",
    bio: "Apapa is Nigeria's premier port city and the commercial gateway of the nation. Home to the Apapa Port — one of the busiest seaports in West Africa — the LGA is the heartbeat of Nigeria's import and export trade. Despite its industrial character, Apapa also houses upscale residential estates and important federal institutions.",
    history: "Apapa's development began in earnest during the colonial period when the British constructed the first deep-water wharf in 1913, transforming Lagos into a major maritime hub. The port expanded significantly after Nigerian independence and today handles billions of dollars in trade annually. Apapa was among the earliest local government areas formally established in 1976. Congestion around the port has been a long-standing infrastructure challenge that multiple administrations have worked to address.",
    landmarks: ["Apapa Port (NPA)", "Tin Can Island Port", "Apapa-Oshodi Expressway", "Apapa Club", "Nigerian Breweries HQ", "NICON Hilton (historical)"],
    knownFor: ["Largest seaport in West Africa", "Industrial and commercial hub", "Import/export trade", "Petroleum tanker traffic"],
    localCouncilDevelopmentAreas: ["Apapa-Iganmu LCDA"],
  },
  {
    id: "badagry",
    name: "Badagry",
    chairman: "Hon. Folorunsho Ambrose",
    officers: [
      { name: "Mr. Segun Williams", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Badagry, Lagos",
    phone: "+234-1-4930600",
    email: "info@badagry.lagosstate.gov.ng",
    zone: "Suburban",
    wards: 11,
    population: "241,093",
    headquarters: "Badagry",
    area: "1,866 km²",
    coordinates: { lat: 6.4154, lng: 2.8895 },
    established: "1976",
    postalCode: "112101",
    bio: "Badagry is one of the oldest and most historically significant towns in Nigeria, located on the border with the Republic of Benin. A former major slave trade port, the town is now a centre for heritage tourism with numerous museums, slave route relics and colonial monuments. Its vast coastline and lagoon system make it one of Lagos State's most scenic destinations.",
    history: "Badagry served as a major transit point of the transatlantic slave trade from the 17th to 19th centuries, with an estimated 500,000 enslaved Africans passing through the Point of No Return. The first storey building in Nigeria was built here in 1845 by Rev. Benjamin Tregaskis. Christianity also entered Nigeria through Badagry when the Rev. Thomas Birch Freeman arrived in 1842. The town's history of slavery, colonial resistance and cultural preservation makes it one of Nigeria's most important heritage sites.",
    landmarks: ["Slave Route / Point of No Return", "Badagry Heritage Museum", "First Storey Building in Nigeria", "Gberefu Beach", "Vlekete Slave Market", "Holy Cross Cathedral (1863)"],
    knownFor: ["Slave trade heritage", "Historical tourism", "Border town with Benin Republic", "Fishing communities", "Coconut plantations"],
    localCouncilDevelopmentAreas: ["Badagry East LCDA", "Badagry West LCDA"],
  },
  {
    id: "epe",
    name: "Epe",
    chairman: "Hon. Suraj Olaposi Edu",
    officers: [
      { name: "Mr. Tunde Fashola", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Epe, Lagos",
    phone: "+234-1-4930700",
    email: "info@epe.lagosstate.gov.ng",
    zone: "Suburban",
    wards: 10,
    population: "200,273",
    headquarters: "Epe",
    area: "1,390 km²",
    coordinates: { lat: 6.5864, lng: 3.9779 },
    established: "1976",
    postalCode: "106101",
    bio: "Epe is a historic town and LGA situated on the northern shores of the Lekki Lagoon, known for its fishing heritage and growing status as an emerging smart city. The Epe Resort and the Lekki Free Zone nearby have positioned the area as a major economic frontier for Lagos State, with major industrial and real estate investments transforming its landscape.",
    history: "Epe has a deep-rooted history tied to the Ijebu Yoruba. In 1853, Oba Kosoko, a former Oba of Lagos, was exiled to Epe after a conflict with the British, establishing a royal court that shaped the town's political culture. The town later became a British protectorate before being incorporated into the Lagos Colony. Epe's fishing traditions remain vibrant and the annual Ojude Oba festival is one of the most celebrated cultural events in the region.",
    landmarks: ["Epe Lagoon", "Epe Resort & Spa", "Lekki Free Zone", "Ojude Oba Festival Grounds", "Royal Palace of Epe", "Epe Fish Market"],
    knownFor: ["Fishing & seafood", "Ojude Oba festival", "Lekki Free Zone proximity", "Emerging smart city", "Lagoon tourism"],
    localCouncilDevelopmentAreas: ["Epe LCDA", "Ikosi-Ejinrin LCDA"],
  },
  {
    id: "eti-osa",
    name: "Eti-Osa",
    chairman: "Hon. Segun Oni",
    officers: [
      { name: "Mrs. Toyin Badmus", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Lekki Phase 1, Lagos",
    phone: "+234-1-4930800",
    email: "info@etiosa.lagosstate.gov.ng",
    zone: "Island",
    wards: 10,
    population: "324,418",
    headquarters: "Lekki",
    area: "468 km²",
    coordinates: { lat: 6.4294, lng: 3.5958 },
    established: "1991",
    postalCode: "101233",
    bio: "Eti-Osa is the wealthiest and most cosmopolitan LGA in Lagos State, encompassing Victoria Island, Ikoyi, Lekki, Ajah and Sangotedo. It is home to the highest concentration of multinational companies, luxury estates, embassies and fine dining establishments in Nigeria. The ongoing Eko Atlantic City development — a brand new city rising from the Atlantic Ocean — is located within its jurisdiction.",
    history: "Eti-Osa was carved out as an LGA in 1991. Victoria Island was developed by the British colonial administration as an exclusive residential area for expatriates and senior officials, and this character largely persisted after independence. Ikoyi similarly developed as an elite enclave. The Lekki axis, which was largely forested peninsula until the 1990s, has since become one of the fastest-growing real estate markets in Africa, driven by private investment and the Lagos State Master Plan.",
    landmarks: ["Victoria Island", "Ikoyi", "Lekki Phase 1", "Eko Atlantic City", "Bar Beach", "National Museum Lagos", "Nike Art Gallery", "Oniru Royal Estate"],
    knownFor: ["Luxury real estate", "Multinational headquarters", "Eko Atlantic City", "Lekki-Epe Expressway", "Nightlife & fine dining"],
    localCouncilDevelopmentAreas: ["Ikoyi-Obalende LCDA", "Iru-Victoria Island LCDA", "Lagos Island East LCDA"],
  },
  {
    id: "ibeju-lekki",
    name: "Ibeju-Lekki",
    chairman: "Hon. Muyiwa Ibile",
    officers: [
      { name: "Mr. Adewale Ogundipe", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Akodo Ise, Lagos",
    phone: "+234-1-4930900",
    email: "info@ibejulekki.lagosstate.gov.ng",
    zone: "Suburban",
    wards: 10,
    population: "117,103",
    headquarters: "Akodo",
    area: "1,126 km²",
    coordinates: { lat: 6.4353, lng: 3.8087 },
    established: "1991",
    postalCode: "106104",
    bio: "Ibeju-Lekki is the fastest-growing LGA in Nigeria and arguably on the African continent. Home to the Dangote Refinery — the largest single-train petroleum refinery in the world — the Lekki Free Zone, Lekki Deep Sea Port and the proposed Lekki International Airport, the LGA is set to become a major industrial powerhouse. Its pristine beaches and lagoons also make it a tourism destination.",
    history: "Ibeju-Lekki was created in 1991 from parts of the old Epe LGA. For decades it was sparsely populated with small fishing and farming communities. The declaration of the Lekki Free Trade Zone in 2006 marked the turning point, attracting hundreds of billions in foreign direct investment. The Dangote Refinery, which has a capacity of 650,000 barrels per day, broke ground in 2016 and is now transforming not just the LGA but the entire Nigerian petroleum sector.",
    landmarks: ["Dangote Refinery", "Lekki Deep Sea Port", "Lekki Free Zone", "La Campagne Tropicana Beach", "Eleko Beach", "Proposed Lekki International Airport"],
    knownFor: ["Dangote Refinery", "Lekki Free Zone", "Fastest-growing LGA in Nigeria", "Pristine beaches", "Massive FDI inflows"],
    localCouncilDevelopmentAreas: ["Ibeju LCDA", "Lekki LCDA"],
  },
  {
    id: "ifako-ijaiye",
    name: "Ifako-Ijaiye",
    chairman: "Hon. Usman Hamzat",
    officers: [
      { name: "Mr. Kola Adewuyi", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Ogba, Lagos",
    phone: "+234-1-4931000",
    email: "info@ifako.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "423,988",
    headquarters: "Ogba",
    area: "81 km²",
    coordinates: { lat: 6.6463, lng: 3.3404 },
    established: "1991",
    postalCode: "100272",
    bio: "Ifako-Ijaiye is a predominantly residential LGA in the northwestern part of Lagos Mainland, covering Ogba, Ifako, Ijaiye and Agbado communities. The Ogba axis in particular has become one of Lagos's most desirable middle-class residential areas, with numerous estates, schools and shopping facilities that have grown steadily over the past two decades.",
    history: "Ifako-Ijaiye was created as a separate LGA in 1991 from the old Agege Local Government. The Agbado area, on the border with Ogun State, has historical roots as a railway junction town dating back to the colonial construction of the Lagos-Kano railway line. The LGA's transformation into a residential zone accelerated in the 1980s and 1990s as Lagosians sought alternatives to crowded Island and central Mainland communities.",
    landmarks: ["Ogba Shopping Mall", "Agbado Railway Station", "Ijaiye Market", "Agidingbi Industrial Area", "Command Children School"],
    knownFor: ["Middle-class residential estates", "Ogba shopping district", "Railway junction history", "Mixed-use urban development"],
    localCouncilDevelopmentAreas: ["Ifako-Ijaye LCDA", "Ojokoro LCDA"],
  },
  {
    id: "ikeja",
    name: "Ikeja",
    chairman: "Hon. Mojeed Balogun",
    officers: [
      { name: "Mrs. Bisi Adeyemi", title: "Head of Local Government Administration" },
      { name: "Mr. Tunde Olawale", title: "Director of Finance" },
    ],
    address: "LG Secretariat, Oba Akinjobi Road, Ikeja, Lagos",
    phone: "+234-1-4931100",
    email: "info@ikeja.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "313,196",
    headquarters: "Ikeja",
    area: "46 km²",
    coordinates: { lat: 6.5950, lng: 3.3381 },
    established: "1976",
    postalCode: "100001",
    bio: "Ikeja is the capital of Lagos State and the administrative headquarters of Lagos State Government. Home to the Murtala Muhammed International Airport, the Lagos State Secretariat at Alausa, the Lagos State House of Assembly and numerous government institutions, Ikeja is the political nerve centre of Nigeria's most commercially significant state. The Ikeja GRA remains one of the most exclusive residential districts in Nigeria.",
    history: "Ikeja's history as a seat of government dates to the colonial era when the British established administrative offices in the area due to its strategic location inland from Lagos Island. After Nigerian independence, Ikeja Airport (later renamed after General Murtala Muhammed) became the primary international gateway into Nigeria. When Lagos State was created in 1967, Ikeja was designated the state capital, a role it continues to fulfil. The 2002 Ikeja Military Cantonment explosion remains one of the most devastating disasters in the LGA's history.",
    landmarks: ["Murtala Muhammed International Airport", "Lagos State Secretariat, Alausa", "Ikeja GRA", "Computer Village", "Lagos State House of Assembly", "Sheraton Lagos Hotel"],
    knownFor: ["Lagos State capital", "International Airport", "Computer Village (tech hub)", "Government institutions", "Ikeja GRA"],
    localCouncilDevelopmentAreas: ["Ojodu LCDA", "Onigbongbo LCDA"],
  },
  {
    id: "ikorodu",
    name: "Ikorodu",
    chairman: "Hon. Wasiu Adesanya",
    officers: [
      { name: "Mr. Lukman Adeyemi", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Lagos Road, Ikorodu, Lagos",
    phone: "+234-1-4931200",
    email: "info@ikorodu.lagosstate.gov.ng",
    zone: "Suburban",
    wards: 12,
    population: "535,619",
    headquarters: "Ikorodu",
    area: "941 km²",
    coordinates: { lat: 6.6194, lng: 3.5061 },
    established: "1976",
    postalCode: "104101",
    bio: "Ikorodu is a rapidly growing LGA located on the northeastern shore of Lagos Lagoon. Once a quiet town known for its fishing and farming communities, Ikorodu has experienced explosive growth driven by its proximity to Lagos Island via the lagoon ferry and the Lagos-Ikorodu Road. It is increasingly attracting manufacturing industries and residential developers seeking land alternatives to congested Lagos Mainland.",
    history: "Ikorodu has ancient roots as a Yoruba town whose people are closely related to the Ijebu-Remo of Ogun State. The town resisted British colonial incursions in the late 19th century before being brought under colonial rule. The Ikorodu water works, built in the early 20th century, was one of the first modern water supply systems outside Lagos Island. The LGA has grown tremendously since the construction of the Ikorodu expressway and the expansion of ferry services across the lagoon.",
    landmarks: ["Ikorodu Ferry Terminal", "Lagos Lagoon Waterfront", "Ijede Fishing Community", "Ikorodu General Hospital", "Lagos-Ikorodu Road"],
    knownFor: ["Lagoon ferry services", "Growing manufacturing zone", "Fishing communities", "Affordable real estate", "Ikorodu traditional festival"],
    localCouncilDevelopmentAreas: ["Ikorodu North LCDA", "Ikorodu West LCDA", "Igbogbo-Bayeku LCDA", "Imota LCDA", "Ikosi-Isheri LCDA"],
  },
  {
    id: "kosofe",
    name: "Kosofe",
    chairman: "Hon. Moyosore Ogunlewe",
    officers: [
      { name: "Mr. Fola Adelekan", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Kosofe, Lagos",
    phone: "+234-1-4931300",
    email: "info@kosofe.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "665,393",
    headquarters: "Kosofe",
    area: "81 km²",
    coordinates: { lat: 6.5833, lng: 3.4167 },
    established: "1991",
    postalCode: "100215",
    bio: "Kosofe LGA covers the areas of Ketu, Ojota, Mile 12, Alapere and Ogudu, making it one of the key transportation and commercial nodes on the Lagos Mainland. Mile 12 International Market — one of the largest fresh produce markets in West Africa — is located here, serving as the primary fresh food distribution hub for Lagos and surrounding states.",
    history: "Kosofe was created in 1991 from the old Mushin LGA. The area's growth is closely tied to the construction of the Lagos-Ibadan Expressway and the development of Mile 12 as a major commercial hub. Ketu has historical roots as a Yoruba settlement and is named after the ancient Ketu Kingdom in present-day Benin Republic from which some of its founders migrated. The area became a major entry point for goods and people from eastern and northern Nigeria.",
    landmarks: ["Mile 12 Market", "Ketu Bus Terminal", "Ojota Bus Terminal", "Ogudu GRA", "Alapere Estate", "NASFAT Headquarters"],
    knownFor: ["Mile 12 produce market", "Major bus terminals (Ketu/Ojota)", "Fresh food distribution hub", "Multicultural population"],
    localCouncilDevelopmentAreas: ["Kosofe LCDA", "Agboyi-Ketu LCDA"],
  },
  {
    id: "lagos-island",
    name: "Lagos Island",
    chairman: "Hon. Idris Aregbe",
    officers: [
      { name: "Mr. Gbolahan Philips", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Igbosere Road, Lagos Island, Lagos",
    phone: "+234-1-4931400",
    email: "info@lagosisland.lagosstate.gov.ng",
    zone: "Island",
    wards: 11,
    population: "209,437",
    headquarters: "Lagos Island",
    area: "8 km²",
    coordinates: { lat: 6.4531, lng: 3.3958 },
    established: "1976",
    postalCode: "101001",
    bio: "Lagos Island is the historic heart of Lagos — the original settlement from which the entire city grew. It hosts the Central Business District, the Balogun Market (one of the largest in West Africa), the Lagos Stock Exchange, the CBN head office and the seat of the old colonial administration. Despite being one of the smallest LGAs by area, it has the highest commercial density in Nigeria.",
    history: "Lagos Island's history spans over 400 years. According to tradition, the Awori people first settled on the island before the Bini Kingdom exerted influence and installed Oba Oduduwa's lineage as royalty around the 16th century. Portuguese traders arrived in the 15th century, giving the area its name 'Lagos' (meaning 'lakes'). The British formally colonised Lagos in 1861 making it a Crown Colony. Lagos Island served as the capital of colonial Nigeria until the capital moved to Abuja in 1991.",
    landmarks: ["Eko Bridge", "Carter Bridge", "Balogun Market", "Lagos Stock Exchange", "Central Bank of Nigeria HQ", "Oba's Palace (Iga Idunganran)", "National Museum Lagos", "Tafawa Balewa Square"],
    knownFor: ["Historic heart of Lagos", "Financial and commercial hub", "Balogun Market", "Oba's Palace", "Nigeria's oldest city core"],
    localCouncilDevelopmentAreas: ["Lagos Island East LCDA", "Ikoyi-Obalende LCDA"],
  },
  {
    id: "lagos-mainland",
    name: "Lagos Mainland",
    chairman: "Hon. Adewale Adegoke",
    officers: [
      { name: "Mr. Segun Adeyemi", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Yaba, Lagos",
    phone: "+234-1-4931500",
    email: "info@lagosmainiland.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "317,720",
    headquarters: "Ebute Metta",
    area: "33 km²",
    coordinates: { lat: 6.5095, lng: 3.3711 },
    established: "1976",
    postalCode: "101212",
    bio: "Lagos Mainland LGA covers Yaba, Ebute Metta, Oyingbo and Makoko — some of the most culturally rich and historically significant communities in Lagos. Yaba is Nigeria's premier technology hub, home to CcHub, dozens of startups and the University of Lagos. Makoko, the famous floating community on the lagoon, is one of the most photographed urban settlements in Africa.",
    history: "Lagos Mainland was the colonial administration's link between Lagos Island and the interior of Nigeria. Ebute Metta developed as a railway terminus town after the construction of the Lagos-Kano railway in 1901. Yaba was developed by the British as a residential area for civil servants and intellectuals, and later housed the Yaba Higher College (1932), the precursor to the University of Lagos. The area has always been associated with education, activism and intellectual life in Nigeria.",
    landmarks: ["University of Lagos", "Yaba Tech (YABATECH)", "Makoko Floating Community", "Yaba Market", "Lagos General Hospital", "National Theatre", "CcHub Nigeria"],
    knownFor: ["Yaba tech ecosystem", "University of Lagos", "Makoko floating village", "Railway history", "Education hub"],
    localCouncilDevelopmentAreas: ["Yaba LCDA"],
  },
  {
    id: "mushin",
    name: "Mushin",
    chairman: "Hon. Bamidele Onaolapo",
    officers: [
      { name: "Mr. Kunle Badmos", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Mushin, Lagos",
    phone: "+234-1-4931600",
    email: "info@mushin.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "633,009",
    headquarters: "Mushin",
    area: "27 km²",
    coordinates: { lat: 6.5277, lng: 3.3561 },
    established: "1976",
    postalCode: "100283",
    bio: "Mushin is one of the most densely populated and commercially active LGAs on the Lagos Mainland. Known for its bustling markets, auto-parts trade and vibrant street culture, Mushin has a strong working-class identity and has produced many of Nigeria's most celebrated artists, musicians and entrepreneurs. The area is synonymous with the Alaba and Ladipo markets — major auto parts trading hubs.",
    history: "Mushin was originally a farming settlement on the outskirts of Lagos before rapid urban migration transformed it from the 1940s onwards. It became a major destination for migrants from Yoruba and Igbo communities seeking work in Lagos. The area developed a reputation for both vibrant commerce and social challenges. In the 1970s and 80s, Mushin was associated with area boys and street gangs, but also with remarkable creative output including contributions to Jùjú and Afrobeats music.",
    landmarks: ["Ladipo Market (Auto Parts)", "Mushin Market", "Idi-Oro Bus Stop", "Papa Ajao Market", "Idi-Araba Hospital Area"],
    knownFor: ["Auto parts trade (Ladipo)", "Vibrant street markets", "Music and nightlife culture", "Working-class heritage"],
    localCouncilDevelopmentAreas: ["Mushin LCDA", "Odi-Olowo/Ojuwoye LCDA"],
  },
  {
    id: "ojo",
    name: "Ojo",
    chairman: "Hon. Abdulkadir Maji",
    officers: [
      { name: "Mr. Tobi Adesanya", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Ojo, Lagos",
    phone: "+234-1-4931700",
    email: "info@ojo.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "598,071",
    headquarters: "Ojo",
    area: "177 km²",
    coordinates: { lat: 6.4698, lng: 3.2067 },
    established: "1976",
    postalCode: "102101",
    bio: "Ojo LGA is a large and diverse local government area along the Lagos Badagry Expressway, encompassing military cantonments, beach communities, and the campuses of Lagos State University and Adeniran Ogunsanya College of Education. The area is also home to the Ojo Military Cantonment — one of the largest military bases in Nigeria — and its coastline along the Bight of Benin offers scenic Atlantic beaches.",
    history: "Ojo has historically been a strategic military and maritime location. The British colonial authorities established a military base here in the early 20th century that grew into the present-day Nigerian Army cantonment. After independence, Ojo emerged as a significant educational centre with LASU establishing its main campus along the expressway. The area's coastline has been used for fishing for centuries by the indigenous Awori communities.",
    landmarks: ["Lagos State University (LASU)", "Ojo Military Cantonment", "Badagry Expressway", "Ojo Beach", "Adeniran Ogunsanya College of Education"],
    knownFor: ["LASU campus", "Military cantonment", "Atlantic coastline", "Expressway communities", "Educational institutions"],
    localCouncilDevelopmentAreas: ["Ojo LCDA", "Oto-Awori LCDA"],
  },
  {
    id: "oshodi-isolo",
    name: "Oshodi-Isolo",
    chairman: "Hon. Bolaji Muse-Ariyibi",
    officers: [
      { name: "Mrs. Sola Adesanya", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Isolo, Lagos",
    phone: "+234-1-4931800",
    email: "info@oshodi.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 12,
    population: "676,366",
    headquarters: "Isolo",
    area: "39 km²",
    coordinates: { lat: 6.5354, lng: 3.3380 },
    established: "1991",
    postalCode: "100213",
    bio: "Oshodi-Isolo is one of the most commercially active transit LGAs in Lagos, home to the famous Oshodi Market and the critical Oshodi transport interchange that connects bus routes across the city. The Isolo industrial estate is one of the oldest and largest in Lagos, housing hundreds of manufacturing and processing firms. The ongoing Oshodi-Apapa Expressway and Oshodi-Abule Egba BRT corridor pass through the LGA.",
    history: "Oshodi developed as a major transport junction from the early 20th century due to its position along key road and rail arteries. The Oshodi Market grew organically as traders exploited the area's transit character. Isolo Industrial Estate was developed by the Lagos State Government in the 1970s as part of an industrialisation drive. The LGA was formally created in 1991. The BRT expansion and road rehabilitation under Governor Fashola in the late 2000s dramatically transformed Oshodi's urban character.",
    landmarks: ["Oshodi Transport Interchange", "Oshodi Market", "Isolo Industrial Estate", "Oshodi-Apapa Expressway", "FESTAC Junction", "Old Toll Gate Area"],
    knownFor: ["Major transport hub", "Oshodi market", "Isolo industrial estate", "BRT corridor", "Commercial density"],
    localCouncilDevelopmentAreas: ["Isolo LCDA", "Ejigbo LCDA"],
  },
  {
    id: "shomolu",
    name: "Shomolu",
    chairman: "Hon. Kehinde Oloyede",
    officers: [
      { name: "Mr. Rotimi Adebayo", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Shomolu, Lagos",
    phone: "+234-1-4931900",
    email: "info@shomolu.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "402,673",
    headquarters: "Shomolu",
    area: "13 km²",
    coordinates: { lat: 6.5356, lng: 3.3861 },
    established: "1991",
    postalCode: "102001",
    bio: "Shomolu LGA encompasses the communities of Shomolu, Bariga, Gbagada and Pedro. The area has a strong identity tied to education, with several respected secondary schools and proximity to the University of Lagos. Gbagada is one of Lagos's most sought-after residential areas for the middle and upper-middle class, with good infrastructure and proximity to both the Island and Mainland.",
    history: "Shomolu was created as a separate LGA in 1991 from the former Lagos Mainland LGA. Bariga has deep historical connections to Lagos's early urban growth, with the community developing alongside the expansion of the railway. The area is associated with some of Nigeria's most prominent educational and media institutions. Gbagada's development as an upscale area accelerated in the late 1990s and 2000s as real estate investors developed estates targeting professionals and diaspora returnees.",
    landmarks: ["Gbagada General Hospital", "Anthony Bus Stop", "Shomolu Market", "Bariga Sports Complex", "Lagos TV (LTV) Headquarters", "Third Mainland Bridge Access"],
    knownFor: ["Gbagada residential estate", "Media institutions", "Education corridor", "Third Mainland Bridge proximity", "Middle-class residential area"],
    localCouncilDevelopmentAreas: ["Shomolu LCDA", "Bariga LCDA"],
  },
  {
    id: "surulere",
    name: "Surulere",
    chairman: "Hon. Tajudeen Ajide",
    officers: [
      { name: "Mr. Kayode Adegboyega", title: "Head of Local Government Administration" },
    ],
    address: "LG Secretariat, Surulere, Lagos",
    phone: "+234-1-4932000",
    email: "info@surulere.lagosstate.gov.ng",
    zone: "Mainland",
    wards: 11,
    population: "503,975",
    headquarters: "Surulere",
    area: "23 km²",
    coordinates: { lat: 6.4969, lng: 3.3481 },
    established: "1976",
    postalCode: "101241",
    bio: "Surulere is one of Lagos's most iconic and culturally vibrant LGAs. Home to the National Stadium — the largest in Nigeria — the National Theatre, the Lagos University Teaching Hospital and the famous Adeniran Ogunsanya Street, Surulere blends sports, arts, healthcare and commerce into a unique urban identity. It remains one of the most beloved residential communities for Lagos's creative and professional class.",
    history: "Surulere was developed as a planned residential estate in the 1950s to house the growing Lagos population. Its name in Yoruba means 'patience yields reward'. The National Stadium was built for the second All-Africa Games in 1973 and hosted several iconic events including the 1977 FESTAC. LUTH was established in 1962 as a teaching affiliate of the University of Lagos. Surulere's creative output — from literature to Afrobeats — has been immense, with Fela Anikulapo-Kuti living and performing in the area.",
    landmarks: ["National Stadium Lagos", "National Theatre", "LUTH (Lagos University Teaching Hospital)", "Adeniran Ogunsanya Street", "Shitta-Bey Mosque", "Teslim Balogun Stadium"],
    knownFor: ["National Stadium", "National Theatre", "Afrobeats culture (Fela Kuti)", "LUTH healthcare", "Creative class residential area"],
    localCouncilDevelopmentAreas: ["Surulere LCDA", "Itire-Ikate LCDA"],
  },
];

export const getLGAById = (id: string) => lgas.find(l => l.id === id);

export const getLGAsByZone = (zone: LGA["zone"]) => lgas.filter(l => l.zone === zone);
